//! ChannelRule DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::AuditMetadata;
use crate::domain::entity::ChannelRule;
use crate::domain::entity::LivechatChatbotCondition;
use crate::domain::entity::LivechatRuleAction;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new ChannelRule
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateChannelRuleDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "channel_id")]
    pub channel_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "regex_url")]
    pub regex_url: String,
    pub action: LivechatRuleAction,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "auto_popup_timer")]
    pub auto_popup_timer: i32,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "chatbot_script_id"
    )]
    pub chatbot_script_id: Option<Uuid>,
    #[serde(alias = "chatbot_enabled_condition")]
    pub chatbot_enabled_condition: LivechatChatbotCondition,
    #[serde(alias = "country_codes")]
    pub country_codes: Vec<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sequence: i32,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a ChannelRule
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateChannelRuleDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "channel_id")]
    pub channel_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "regex_url")]
    pub regex_url: String,
    pub action: LivechatRuleAction,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "auto_popup_timer")]
    pub auto_popup_timer: i32,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "chatbot_script_id"
    )]
    pub chatbot_script_id: Option<Uuid>,
    #[serde(alias = "chatbot_enabled_condition")]
    pub chatbot_enabled_condition: LivechatChatbotCondition,
    #[serde(alias = "country_codes")]
    pub country_codes: Vec<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sequence: i32,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a ChannelRule
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchChannelRuleDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(skip_serializing_if = "Option::is_none", alias = "channel_id")]
    pub channel_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "regex_url")]
    pub regex_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub action: Option<LivechatRuleAction>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "auto_popup_timer")]
    pub auto_popup_timer: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "chatbot_script_id")]
    pub chatbot_script_id: Option<Uuid>,
    #[serde(
        skip_serializing_if = "Option::is_none",
        alias = "chatbot_enabled_condition"
    )]
    pub chatbot_enabled_condition: Option<LivechatChatbotCondition>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "country_codes")]
    pub country_codes: Option<Vec<String>>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sequence: Option<i32>,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
}

impl PatchChannelRuleDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.channel_id.is_some()
            || self.regex_url.is_some()
            || self.action.is_some()
            || self.auto_popup_timer.is_some()
            || self.chatbot_script_id.is_some()
            || self.chatbot_enabled_condition.is_some()
            || self.country_codes.is_some()
            || self.sequence.is_some()
            || self.company_id.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for ChannelRule entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ChannelRuleResponseDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub channel_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub regex_url: String,
    pub action: LivechatRuleAction,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub auto_popup_timer: i32,
    pub chatbot_script_id: Option<Uuid>,
    pub chatbot_enabled_condition: LivechatChatbotCondition,
    pub country_codes: Vec<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sequence: i32,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub company_id: Uuid,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for ChannelRule entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ChannelRuleListResponseDto {
    /// List of items
    pub items: Vec<ChannelRuleResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl ChannelRuleListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<ChannelRuleResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ChannelRuleSummaryDto {
    pub id: Uuid,
    pub channel_id: Uuid,
    pub regex_url: String,
    pub action: LivechatRuleAction,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<ChannelRule> for ChannelRuleResponseDto {
    fn from(entity: ChannelRule) -> Self {
        Self {
            id: entity.id,
            channel_id: entity.channel_id,
            regex_url: entity.regex_url,
            action: entity.action,
            auto_popup_timer: entity.auto_popup_timer,
            chatbot_script_id: entity.chatbot_script_id,
            chatbot_enabled_condition: entity.chatbot_enabled_condition,
            country_codes: entity.country_codes,
            sequence: entity.sequence,
            company_id: entity.company_id,
            metadata: entity.metadata,
        }
    }
}

impl From<ChannelRule> for ChannelRuleSummaryDto {
    fn from(entity: ChannelRule) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            channel_id: entity.channel_id,
            regex_url: entity.regex_url,
            action: entity.action,
            created_at,
        }
    }
}

impl From<CreateChannelRuleDto> for ChannelRule {
    fn from(dto: CreateChannelRuleDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            channel_id: dto.channel_id,
            regex_url: dto.regex_url,
            action: dto.action,
            auto_popup_timer: dto.auto_popup_timer,
            chatbot_script_id: dto.chatbot_script_id,
            chatbot_enabled_condition: dto.chatbot_enabled_condition,
            country_codes: dto.country_codes,
            sequence: dto.sequence,
            company_id: dto.company_id,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&ChannelRule> for ChannelRuleResponseDto {
    fn from(entity: &ChannelRule) -> Self {
        Self {
            id: entity.id.clone(),
            channel_id: entity.channel_id.clone(),
            regex_url: entity.regex_url.clone(),
            action: entity.action.clone(),
            auto_popup_timer: entity.auto_popup_timer.clone(),
            chatbot_script_id: entity.chatbot_script_id.clone(),
            chatbot_enabled_condition: entity.chatbot_enabled_condition.clone(),
            country_codes: entity.country_codes.clone(),
            sequence: entity.sequence.clone(),
            company_id: entity.company_id.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateChannelRuleDto> for ChannelRule {
    fn from_create_dto(dto: CreateChannelRuleDto) -> backbone_core::ServiceResult<Self> {
        Ok(ChannelRule::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateChannelRuleDto> for ChannelRule {
    fn apply_update(mut self, dto: UpdateChannelRuleDto) -> backbone_core::ServiceResult<Self> {
        self.channel_id = dto.channel_id;
        self.regex_url = dto.regex_url;
        self.action = dto.action;
        self.auto_popup_timer = dto.auto_popup_timer;
        self.chatbot_script_id = dto.chatbot_script_id;
        self.chatbot_enabled_condition = dto.chatbot_enabled_condition;
        self.country_codes = dto.country_codes;
        self.sequence = dto.sequence;
        self.company_id = dto.company_id;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to ChannelRule here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
