//! ChatbotStepTrigger DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::ChatbotStepTrigger;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new ChatbotStepTrigger
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateChatbotStepTriggerDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "answer_id")]
    pub answer_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "target_step_id")]
    pub target_step_id: Uuid,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a ChatbotStepTrigger
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateChatbotStepTriggerDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "answer_id")]
    pub answer_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "target_step_id")]
    pub target_step_id: Uuid,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a ChatbotStepTrigger
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchChatbotStepTriggerDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "answer_id")]
    pub answer_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "target_step_id")]
    pub target_step_id: Option<Uuid>,
}

impl PatchChatbotStepTriggerDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.answer_id.is_some() || self.target_step_id.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for ChatbotStepTrigger entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ChatbotStepTriggerResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub answer_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub target_step_id: Uuid,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for ChatbotStepTrigger entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ChatbotStepTriggerListResponseDto {
    /// List of items
    pub items: Vec<ChatbotStepTriggerResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl ChatbotStepTriggerListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<ChatbotStepTriggerResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ChatbotStepTriggerSummaryDto {
    pub id: Uuid,
    pub answer_id: Uuid,
    pub target_step_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<ChatbotStepTrigger> for ChatbotStepTriggerResponseDto {
    fn from(entity: ChatbotStepTrigger) -> Self {
        Self {
            id: entity.id,
            answer_id: entity.answer_id,
            target_step_id: entity.target_step_id,
            metadata: entity.metadata,
        }
    }
}

impl From<ChatbotStepTrigger> for ChatbotStepTriggerSummaryDto {
    fn from(entity: ChatbotStepTrigger) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            answer_id: entity.answer_id,
            target_step_id: entity.target_step_id,
            created_at,
        }
    }
}

impl From<CreateChatbotStepTriggerDto> for ChatbotStepTrigger {
    fn from(dto: CreateChatbotStepTriggerDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            answer_id: dto.answer_id,
            target_step_id: dto.target_step_id,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&ChatbotStepTrigger> for ChatbotStepTriggerResponseDto {
    fn from(entity: &ChatbotStepTrigger) -> Self {
        Self {
            id: entity.id.clone(),
            answer_id: entity.answer_id.clone(),
            target_step_id: entity.target_step_id.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateChatbotStepTriggerDto> for ChatbotStepTrigger {
    fn from_create_dto(dto: CreateChatbotStepTriggerDto) -> backbone_core::ServiceResult<Self> {
        Ok(ChatbotStepTrigger::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateChatbotStepTriggerDto> for ChatbotStepTrigger {
    fn apply_update(mut self, dto: UpdateChatbotStepTriggerDto) -> backbone_core::ServiceResult<Self> {
        self.answer_id = dto.answer_id;
        self.target_step_id = dto.target_step_id;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to ChatbotStepTrigger here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
