//! ChatbotStep DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::ChatbotStep;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::LivechatStepType;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new ChatbotStep
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateChatbotStepDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "chatbot_script_id")]
    pub chatbot_script_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sequence: i32,
    #[serde(alias = "step_type")]
    pub step_type: LivechatStepType,
    #[cfg_attr(feature = "validation", validate(length(max = 5000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(alias = "expertise_tag_ids")]
    pub expertise_tag_ids: Vec<Uuid>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a ChatbotStep
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateChatbotStepDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "chatbot_script_id")]
    pub chatbot_script_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sequence: i32,
    #[serde(alias = "step_type")]
    pub step_type: LivechatStepType,
    #[cfg_attr(feature = "validation", validate(length(max = 5000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(alias = "expertise_tag_ids")]
    pub expertise_tag_ids: Vec<Uuid>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a ChatbotStep
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchChatbotStepDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "chatbot_script_id")]
    pub chatbot_script_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sequence: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "step_type")]
    pub step_type: Option<LivechatStepType>,
    #[cfg_attr(feature = "validation", validate(length(max = 5000)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "expertise_tag_ids")]
    pub expertise_tag_ids: Option<Vec<Uuid>>,
}

impl PatchChatbotStepDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.chatbot_script_id.is_some() || self.sequence.is_some() || self.step_type.is_some() || self.message.is_some() || self.expertise_tag_ids.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for ChatbotStep entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ChatbotStepResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub chatbot_script_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sequence: i32,
    pub step_type: LivechatStepType,
    pub message: Option<String>,
    pub expertise_tag_ids: Vec<Uuid>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for ChatbotStep entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ChatbotStepListResponseDto {
    /// List of items
    pub items: Vec<ChatbotStepResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl ChatbotStepListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<ChatbotStepResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ChatbotStepSummaryDto {
    pub id: Uuid,
    pub chatbot_script_id: Uuid,
    pub sequence: i32,
    pub step_type: LivechatStepType,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<ChatbotStep> for ChatbotStepResponseDto {
    fn from(entity: ChatbotStep) -> Self {
        Self {
            id: entity.id,
            chatbot_script_id: entity.chatbot_script_id,
            sequence: entity.sequence,
            step_type: entity.step_type,
            message: entity.message,
            expertise_tag_ids: entity.expertise_tag_ids,
            metadata: entity.metadata,
        }
    }
}

impl From<ChatbotStep> for ChatbotStepSummaryDto {
    fn from(entity: ChatbotStep) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            chatbot_script_id: entity.chatbot_script_id,
            sequence: entity.sequence,
            step_type: entity.step_type,
            created_at,
        }
    }
}

impl From<CreateChatbotStepDto> for ChatbotStep {
    fn from(dto: CreateChatbotStepDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            chatbot_script_id: dto.chatbot_script_id,
            sequence: dto.sequence,
            step_type: dto.step_type,
            message: dto.message,
            expertise_tag_ids: dto.expertise_tag_ids,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&ChatbotStep> for ChatbotStepResponseDto {
    fn from(entity: &ChatbotStep) -> Self {
        Self {
            id: entity.id.clone(),
            chatbot_script_id: entity.chatbot_script_id.clone(),
            sequence: entity.sequence.clone(),
            step_type: entity.step_type.clone(),
            message: entity.message.clone(),
            expertise_tag_ids: entity.expertise_tag_ids.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateChatbotStepDto> for ChatbotStep {
    fn from_create_dto(dto: CreateChatbotStepDto) -> backbone_core::ServiceResult<Self> {
        Ok(ChatbotStep::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateChatbotStepDto> for ChatbotStep {
    fn apply_update(mut self, dto: UpdateChatbotStepDto) -> backbone_core::ServiceResult<Self> {
        self.chatbot_script_id = dto.chatbot_script_id;
        self.sequence = dto.sequence;
        self.step_type = dto.step_type;
        self.message = dto.message;
        self.expertise_tag_ids = dto.expertise_tag_ids;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to ChatbotStep here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
