//! ChatbotAnswer DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::ChatbotAnswer;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new ChatbotAnswer
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateChatbotAnswerDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "question_step_id")]
    pub question_step_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sequence: i32,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub label: String,
    #[cfg_attr(feature = "validation", validate(url))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "redirect_url")]
    pub redirect_url: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a ChatbotAnswer
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateChatbotAnswerDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "question_step_id")]
    pub question_step_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sequence: i32,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub label: String,
    #[cfg_attr(feature = "validation", validate(url))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "redirect_url")]
    pub redirect_url: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a ChatbotAnswer
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchChatbotAnswerDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "question_step_id")]
    pub question_step_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sequence: Option<i32>,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[cfg_attr(feature = "validation", validate(url))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "redirect_url")]
    pub redirect_url: Option<String>,
}

impl PatchChatbotAnswerDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.question_step_id.is_some() || self.sequence.is_some() || self.label.is_some() || self.redirect_url.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for ChatbotAnswer entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ChatbotAnswerResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub question_step_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sequence: i32,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub label: String,
    pub redirect_url: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for ChatbotAnswer entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ChatbotAnswerListResponseDto {
    /// List of items
    pub items: Vec<ChatbotAnswerResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl ChatbotAnswerListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<ChatbotAnswerResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ChatbotAnswerSummaryDto {
    pub id: Uuid,
    pub question_step_id: Uuid,
    pub sequence: i32,
    pub label: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<ChatbotAnswer> for ChatbotAnswerResponseDto {
    fn from(entity: ChatbotAnswer) -> Self {
        Self {
            id: entity.id,
            question_step_id: entity.question_step_id,
            sequence: entity.sequence,
            label: entity.label,
            redirect_url: entity.redirect_url,
            metadata: entity.metadata,
        }
    }
}

impl From<ChatbotAnswer> for ChatbotAnswerSummaryDto {
    fn from(entity: ChatbotAnswer) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            question_step_id: entity.question_step_id,
            sequence: entity.sequence,
            label: entity.label,
            created_at,
        }
    }
}

impl From<CreateChatbotAnswerDto> for ChatbotAnswer {
    fn from(dto: CreateChatbotAnswerDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            question_step_id: dto.question_step_id,
            sequence: dto.sequence,
            label: dto.label,
            redirect_url: dto.redirect_url,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&ChatbotAnswer> for ChatbotAnswerResponseDto {
    fn from(entity: &ChatbotAnswer) -> Self {
        Self {
            id: entity.id.clone(),
            question_step_id: entity.question_step_id.clone(),
            sequence: entity.sequence.clone(),
            label: entity.label.clone(),
            redirect_url: entity.redirect_url.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateChatbotAnswerDto> for ChatbotAnswer {
    fn from_create_dto(dto: CreateChatbotAnswerDto) -> backbone_core::ServiceResult<Self> {
        Ok(ChatbotAnswer::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateChatbotAnswerDto> for ChatbotAnswer {
    fn apply_update(mut self, dto: UpdateChatbotAnswerDto) -> backbone_core::ServiceResult<Self> {
        self.question_step_id = dto.question_step_id;
        self.sequence = dto.sequence;
        self.label = dto.label;
        self.redirect_url = dto.redirect_url;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to ChatbotAnswer here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
