//! ChatbotMessage DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::ChatbotMessage;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new ChatbotMessage
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateChatbotMessageDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "session_id")]
    pub session_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "step_id")]
    pub step_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "carrier_message_id")]
    pub carrier_message_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "selected_answer_id")]
    pub selected_answer_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 2000)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "visitor_answer")]
    pub visitor_answer: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a ChatbotMessage
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateChatbotMessageDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "session_id")]
    pub session_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "step_id")]
    pub step_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "carrier_message_id")]
    pub carrier_message_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "selected_answer_id")]
    pub selected_answer_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 2000)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "visitor_answer")]
    pub visitor_answer: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a ChatbotMessage
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchChatbotMessageDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "session_id")]
    pub session_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "step_id")]
    pub step_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "carrier_message_id")]
    pub carrier_message_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "selected_answer_id")]
    pub selected_answer_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 2000)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "visitor_answer")]
    pub visitor_answer: Option<String>,
}

impl PatchChatbotMessageDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.session_id.is_some() || self.step_id.is_some() || self.carrier_message_id.is_some() || self.selected_answer_id.is_some() || self.visitor_answer.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for ChatbotMessage entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ChatbotMessageResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub session_id: Uuid,
    pub step_id: Option<Uuid>,
    pub carrier_message_id: Option<String>,
    pub selected_answer_id: Option<Uuid>,
    pub visitor_answer: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub created_at: DateTime<Utc>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for ChatbotMessage entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ChatbotMessageListResponseDto {
    /// List of items
    pub items: Vec<ChatbotMessageResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl ChatbotMessageListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<ChatbotMessageResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ChatbotMessageSummaryDto {
    pub id: Uuid,
    pub session_id: Uuid,
    pub step_id: Option<Uuid>,
    pub carrier_message_id: Option<String>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<ChatbotMessage> for ChatbotMessageResponseDto {
    fn from(entity: ChatbotMessage) -> Self {
        Self {
            id: entity.id,
            session_id: entity.session_id,
            step_id: entity.step_id,
            carrier_message_id: entity.carrier_message_id,
            selected_answer_id: entity.selected_answer_id,
            visitor_answer: entity.visitor_answer,
            created_at: entity.created_at,
            metadata: entity.metadata,
        }
    }
}

impl From<ChatbotMessage> for ChatbotMessageSummaryDto {
    fn from(entity: ChatbotMessage) -> Self {
        Self {
            id: entity.id,
            session_id: entity.session_id,
            step_id: entity.step_id,
            carrier_message_id: entity.carrier_message_id,
            created_at: Some(entity.created_at),
        }
    }
}

impl From<CreateChatbotMessageDto> for ChatbotMessage {
    fn from(dto: CreateChatbotMessageDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            session_id: dto.session_id,
            step_id: dto.step_id,
            carrier_message_id: dto.carrier_message_id,
            selected_answer_id: dto.selected_answer_id,
            visitor_answer: dto.visitor_answer,
            created_at: Utc::now(),
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&ChatbotMessage> for ChatbotMessageResponseDto {
    fn from(entity: &ChatbotMessage) -> Self {
        Self {
            id: entity.id.clone(),
            session_id: entity.session_id.clone(),
            step_id: entity.step_id.clone(),
            carrier_message_id: entity.carrier_message_id.clone(),
            selected_answer_id: entity.selected_answer_id.clone(),
            visitor_answer: entity.visitor_answer.clone(),
            created_at: entity.created_at.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateChatbotMessageDto> for ChatbotMessage {
    fn from_create_dto(dto: CreateChatbotMessageDto) -> backbone_core::ServiceResult<Self> {
        Ok(ChatbotMessage::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateChatbotMessageDto> for ChatbotMessage {
    fn apply_update(mut self, dto: UpdateChatbotMessageDto) -> backbone_core::ServiceResult<Self> {
        self.session_id = dto.session_id;
        self.step_id = dto.step_id;
        self.carrier_message_id = dto.carrier_message_id;
        self.selected_answer_id = dto.selected_answer_id;
        self.visitor_answer = dto.visitor_answer;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to ChatbotMessage here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
