//! LivechatAuditLog DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::AuditMetadata;
use crate::domain::entity::LivechatAuditEvent;
use crate::domain::entity::LivechatAuditLog;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new LivechatAuditLog
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateLivechatAuditLogDto {
    pub event: LivechatAuditEvent,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub actor: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "subject_type"
    )]
    pub subject_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "subject_id")]
    pub subject_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub detail: Option<serde_json::Value>,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a LivechatAuditLog
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateLivechatAuditLogDto {
    pub event: LivechatAuditEvent,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub actor: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "subject_type"
    )]
    pub subject_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "subject_id")]
    pub subject_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub detail: Option<serde_json::Value>,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a LivechatAuditLog
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchLivechatAuditLogDto {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub event: Option<LivechatAuditEvent>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub actor: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "subject_type")]
    pub subject_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "subject_id")]
    pub subject_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub detail: Option<serde_json::Value>,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
}

impl PatchLivechatAuditLogDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.event.is_some()
            || self.actor.is_some()
            || self.subject_type.is_some()
            || self.subject_id.is_some()
            || self.detail.is_some()
            || self.company_id.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for LivechatAuditLog entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct LivechatAuditLogResponseDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub id: Uuid,
    pub event: LivechatAuditEvent,
    pub actor: Option<Uuid>,
    pub subject_type: Option<String>,
    pub subject_id: Option<Uuid>,
    pub detail: Option<serde_json::Value>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub created_at: DateTime<Utc>,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub company_id: Uuid,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for LivechatAuditLog entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct LivechatAuditLogListResponseDto {
    /// List of items
    pub items: Vec<LivechatAuditLogResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl LivechatAuditLogListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(
        items: Vec<LivechatAuditLogResponseDto>,
        total: u64,
        page: u32,
        per_page: u32,
    ) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct LivechatAuditLogSummaryDto {
    pub id: Uuid,
    pub event: LivechatAuditEvent,
    pub actor: Option<Uuid>,
    pub subject_type: Option<String>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<LivechatAuditLog> for LivechatAuditLogResponseDto {
    fn from(entity: LivechatAuditLog) -> Self {
        Self {
            id: entity.id,
            event: entity.event,
            actor: entity.actor,
            subject_type: entity.subject_type,
            subject_id: entity.subject_id,
            detail: entity.detail,
            created_at: entity.created_at,
            company_id: entity.company_id,
            metadata: entity.metadata,
        }
    }
}

impl From<LivechatAuditLog> for LivechatAuditLogSummaryDto {
    fn from(entity: LivechatAuditLog) -> Self {
        Self {
            id: entity.id,
            event: entity.event,
            actor: entity.actor,
            subject_type: entity.subject_type,
            created_at: Some(entity.created_at),
        }
    }
}

impl From<CreateLivechatAuditLogDto> for LivechatAuditLog {
    fn from(dto: CreateLivechatAuditLogDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            event: dto.event,
            actor: dto.actor,
            subject_type: dto.subject_type,
            subject_id: dto.subject_id,
            detail: dto.detail,
            created_at: Utc::now(),
            company_id: dto.company_id,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&LivechatAuditLog> for LivechatAuditLogResponseDto {
    fn from(entity: &LivechatAuditLog) -> Self {
        Self {
            id: entity.id.clone(),
            event: entity.event.clone(),
            actor: entity.actor.clone(),
            subject_type: entity.subject_type.clone(),
            subject_id: entity.subject_id.clone(),
            detail: entity.detail.clone(),
            created_at: entity.created_at.clone(),
            company_id: entity.company_id.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateLivechatAuditLogDto> for LivechatAuditLog {
    fn from_create_dto(dto: CreateLivechatAuditLogDto) -> backbone_core::ServiceResult<Self> {
        Ok(LivechatAuditLog::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateLivechatAuditLogDto> for LivechatAuditLog {
    fn apply_update(
        mut self,
        dto: UpdateLivechatAuditLogDto,
    ) -> backbone_core::ServiceResult<Self> {
        self.event = dto.event;
        self.actor = dto.actor;
        self.subject_type = dto.subject_type;
        self.subject_id = dto.subject_id;
        self.detail = dto.detail;
        self.company_id = dto.company_id;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to LivechatAuditLog here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
