//! MemberHistory DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::AuditMetadata;
use crate::domain::entity::LivechatPersona;
use crate::domain::entity::MemberHistory;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new MemberHistory
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateMemberHistoryDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "session_id")]
    pub session_id: Uuid,
    pub persona: LivechatPersona,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "operator_user_id"
    )]
    pub operator_user_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "visitor_key"
    )]
    pub visitor_key: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "chatbot_script_id"
    )]
    pub chatbot_script_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "joined_at")]
    pub joined_at: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "left_at")]
    pub left_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "message_count")]
    pub message_count: i32,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "response_time_secs"
    )]
    pub response_time_secs: Option<i32>,
    #[serde(alias = "expertise_names")]
    pub expertise_names: Vec<String>,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a MemberHistory
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateMemberHistoryDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "session_id")]
    pub session_id: Uuid,
    pub persona: LivechatPersona,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "operator_user_id"
    )]
    pub operator_user_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "visitor_key"
    )]
    pub visitor_key: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "chatbot_script_id"
    )]
    pub chatbot_script_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "joined_at")]
    pub joined_at: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "left_at")]
    pub left_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "message_count")]
    pub message_count: i32,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "response_time_secs"
    )]
    pub response_time_secs: Option<i32>,
    #[serde(alias = "expertise_names")]
    pub expertise_names: Vec<String>,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a MemberHistory
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchMemberHistoryDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(skip_serializing_if = "Option::is_none", alias = "session_id")]
    pub session_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub persona: Option<LivechatPersona>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "operator_user_id")]
    pub operator_user_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "visitor_key")]
    pub visitor_key: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "chatbot_script_id")]
    pub chatbot_script_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "joined_at")]
    pub joined_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "left_at")]
    pub left_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "message_count")]
    pub message_count: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "response_time_secs")]
    pub response_time_secs: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "expertise_names")]
    pub expertise_names: Option<Vec<String>>,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
}

impl PatchMemberHistoryDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.session_id.is_some()
            || self.persona.is_some()
            || self.operator_user_id.is_some()
            || self.visitor_key.is_some()
            || self.chatbot_script_id.is_some()
            || self.joined_at.is_some()
            || self.left_at.is_some()
            || self.message_count.is_some()
            || self.response_time_secs.is_some()
            || self.expertise_names.is_some()
            || self.company_id.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for MemberHistory entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MemberHistoryResponseDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub session_id: Uuid,
    pub persona: LivechatPersona,
    pub operator_user_id: Option<Uuid>,
    pub visitor_key: Option<String>,
    pub chatbot_script_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub joined_at: DateTime<Utc>,
    pub left_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub message_count: i32,
    pub response_time_secs: Option<i32>,
    pub expertise_names: Vec<String>,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub company_id: Uuid,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for MemberHistory entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MemberHistoryListResponseDto {
    /// List of items
    pub items: Vec<MemberHistoryResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl MemberHistoryListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<MemberHistoryResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MemberHistorySummaryDto {
    pub id: Uuid,
    pub session_id: Uuid,
    pub persona: LivechatPersona,
    pub operator_user_id: Option<Uuid>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<MemberHistory> for MemberHistoryResponseDto {
    fn from(entity: MemberHistory) -> Self {
        Self {
            id: entity.id,
            session_id: entity.session_id,
            persona: entity.persona,
            operator_user_id: entity.operator_user_id,
            visitor_key: entity.visitor_key,
            chatbot_script_id: entity.chatbot_script_id,
            joined_at: entity.joined_at,
            left_at: entity.left_at,
            message_count: entity.message_count,
            response_time_secs: entity.response_time_secs,
            expertise_names: entity.expertise_names,
            company_id: entity.company_id,
            metadata: entity.metadata,
        }
    }
}

impl From<MemberHistory> for MemberHistorySummaryDto {
    fn from(entity: MemberHistory) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            session_id: entity.session_id,
            persona: entity.persona,
            operator_user_id: entity.operator_user_id,
            created_at,
        }
    }
}

impl From<CreateMemberHistoryDto> for MemberHistory {
    fn from(dto: CreateMemberHistoryDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            session_id: dto.session_id,
            persona: dto.persona,
            operator_user_id: dto.operator_user_id,
            visitor_key: dto.visitor_key,
            chatbot_script_id: dto.chatbot_script_id,
            joined_at: dto.joined_at,
            left_at: dto.left_at,
            message_count: dto.message_count,
            response_time_secs: dto.response_time_secs,
            expertise_names: dto.expertise_names,
            company_id: dto.company_id,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&MemberHistory> for MemberHistoryResponseDto {
    fn from(entity: &MemberHistory) -> Self {
        Self {
            id: entity.id.clone(),
            session_id: entity.session_id.clone(),
            persona: entity.persona.clone(),
            operator_user_id: entity.operator_user_id.clone(),
            visitor_key: entity.visitor_key.clone(),
            chatbot_script_id: entity.chatbot_script_id.clone(),
            joined_at: entity.joined_at.clone(),
            left_at: entity.left_at.clone(),
            message_count: entity.message_count.clone(),
            response_time_secs: entity.response_time_secs.clone(),
            expertise_names: entity.expertise_names.clone(),
            company_id: entity.company_id.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateMemberHistoryDto> for MemberHistory {
    fn from_create_dto(dto: CreateMemberHistoryDto) -> backbone_core::ServiceResult<Self> {
        Ok(MemberHistory::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateMemberHistoryDto> for MemberHistory {
    fn apply_update(mut self, dto: UpdateMemberHistoryDto) -> backbone_core::ServiceResult<Self> {
        self.session_id = dto.session_id;
        self.persona = dto.persona;
        self.operator_user_id = dto.operator_user_id;
        self.visitor_key = dto.visitor_key;
        self.chatbot_script_id = dto.chatbot_script_id;
        self.joined_at = dto.joined_at;
        self.left_at = dto.left_at;
        self.message_count = dto.message_count;
        self.response_time_secs = dto.response_time_secs;
        self.expertise_names = dto.expertise_names;
        self.company_id = dto.company_id;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to MemberHistory here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
