//! DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides DTOs for the presentation layer,
//! with validation and OpenAPI schema support.

pub mod channel_dto;
pub mod channel_member_dto;
pub mod channel_rule_dto;
pub mod chatbot_answer_dto;
pub mod chatbot_message_dto;
pub mod chatbot_script_dto;
pub mod chatbot_step_dto;
pub mod chatbot_step_trigger_dto;
pub mod conversation_tag_dto;
pub mod expertise_tag_dto;
pub mod livechat_audit_log_dto;
pub mod member_history_dto;
pub mod operator_expertise_dto;
pub mod operator_profile_dto;
pub mod rating_dto;
pub mod session_dto;
pub mod session_tag_dto;

// Re-exports
pub use channel_dto::{
    CreateChannelDto,
    UpdateChannelDto,
    PatchChannelDto,
    ChannelResponseDto,
    ChannelListResponseDto,
    ChannelSummaryDto,
};
pub use channel_member_dto::{
    CreateChannelMemberDto,
    UpdateChannelMemberDto,
    PatchChannelMemberDto,
    ChannelMemberResponseDto,
    ChannelMemberListResponseDto,
    ChannelMemberSummaryDto,
};
pub use channel_rule_dto::{
    CreateChannelRuleDto,
    UpdateChannelRuleDto,
    PatchChannelRuleDto,
    ChannelRuleResponseDto,
    ChannelRuleListResponseDto,
    ChannelRuleSummaryDto,
};
pub use chatbot_answer_dto::{
    CreateChatbotAnswerDto,
    UpdateChatbotAnswerDto,
    PatchChatbotAnswerDto,
    ChatbotAnswerResponseDto,
    ChatbotAnswerListResponseDto,
    ChatbotAnswerSummaryDto,
};
pub use chatbot_message_dto::{
    CreateChatbotMessageDto,
    UpdateChatbotMessageDto,
    PatchChatbotMessageDto,
    ChatbotMessageResponseDto,
    ChatbotMessageListResponseDto,
    ChatbotMessageSummaryDto,
};
pub use chatbot_script_dto::{
    CreateChatbotScriptDto,
    UpdateChatbotScriptDto,
    PatchChatbotScriptDto,
    ChatbotScriptResponseDto,
    ChatbotScriptListResponseDto,
    ChatbotScriptSummaryDto,
};
pub use chatbot_step_dto::{
    CreateChatbotStepDto,
    UpdateChatbotStepDto,
    PatchChatbotStepDto,
    ChatbotStepResponseDto,
    ChatbotStepListResponseDto,
    ChatbotStepSummaryDto,
};
pub use chatbot_step_trigger_dto::{
    CreateChatbotStepTriggerDto,
    UpdateChatbotStepTriggerDto,
    PatchChatbotStepTriggerDto,
    ChatbotStepTriggerResponseDto,
    ChatbotStepTriggerListResponseDto,
    ChatbotStepTriggerSummaryDto,
};
pub use conversation_tag_dto::{
    CreateConversationTagDto,
    UpdateConversationTagDto,
    PatchConversationTagDto,
    ConversationTagResponseDto,
    ConversationTagListResponseDto,
    ConversationTagSummaryDto,
};
pub use expertise_tag_dto::{
    CreateExpertiseTagDto,
    UpdateExpertiseTagDto,
    PatchExpertiseTagDto,
    ExpertiseTagResponseDto,
    ExpertiseTagListResponseDto,
    ExpertiseTagSummaryDto,
};
pub use livechat_audit_log_dto::{
    CreateLivechatAuditLogDto,
    UpdateLivechatAuditLogDto,
    PatchLivechatAuditLogDto,
    LivechatAuditLogResponseDto,
    LivechatAuditLogListResponseDto,
    LivechatAuditLogSummaryDto,
};
pub use member_history_dto::{
    CreateMemberHistoryDto,
    UpdateMemberHistoryDto,
    PatchMemberHistoryDto,
    MemberHistoryResponseDto,
    MemberHistoryListResponseDto,
    MemberHistorySummaryDto,
};
pub use operator_expertise_dto::{
    CreateOperatorExpertiseDto,
    UpdateOperatorExpertiseDto,
    PatchOperatorExpertiseDto,
    OperatorExpertiseResponseDto,
    OperatorExpertiseListResponseDto,
    OperatorExpertiseSummaryDto,
};
pub use operator_profile_dto::{
    CreateOperatorProfileDto,
    UpdateOperatorProfileDto,
    PatchOperatorProfileDto,
    OperatorProfileResponseDto,
    OperatorProfileListResponseDto,
    OperatorProfileSummaryDto,
};
pub use rating_dto::{
    CreateRatingDto,
    UpdateRatingDto,
    PatchRatingDto,
    RatingResponseDto,
    RatingListResponseDto,
    RatingSummaryDto,
};
pub use session_dto::{
    CreateSessionDto,
    UpdateSessionDto,
    PatchSessionDto,
    SessionResponseDto,
    SessionListResponseDto,
    SessionSummaryDto,
};
pub use session_tag_dto::{
    CreateSessionTagDto,
    UpdateSessionTagDto,
    PatchSessionTagDto,
    SessionTagResponseDto,
    SessionTagListResponseDto,
    SessionTagSummaryDto,
};

// Common pagination types
use serde::Serialize;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

/// Pagination parameters for list requests
#[derive(Debug, Clone, Default, serde::Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
pub struct PaginationParams {
    /// Page number (1-indexed)
    #[serde(default = "default_page")]
    pub page: u32,
    /// Items per page
    #[serde(default = "default_per_page")]
    pub per_page: u32,
    /// Field to sort by
    pub sort_by: Option<String>,
    /// Sort order (asc/desc)
    pub sort_order: Option<String>,
}

fn default_page() -> u32 { 1 }
fn default_per_page() -> u32 { 20 }

/// API response wrapper
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ApiResponse<T> {
    pub success: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<T>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<ApiError>,
}

#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
pub struct ApiError {
    pub code: String,
    pub message: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub details: Option<serde_json::Value>,
}

impl<T> ApiResponse<T> {
    pub fn ok(data: T) -> Self {
        Self { success: true, data: Some(data), error: None }
    }

    pub fn err(code: impl Into<String>, message: impl Into<String>) -> Self {
        Self {
            success: false,
            data: None,
            error: Some(ApiError {
                code: code.into(),
                message: message.into(),
                details: None,
            }),
        }
    }
}
