//! OperatorProfile DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::AuditMetadata;
use crate::domain::entity::OperatorProfile;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new OperatorProfile
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateOperatorProfileDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "user_id")]
    pub user_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "display_name"
    )]
    pub display_name: Option<String>,
    pub languages: Vec<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "last_heartbeat_at"
    )]
    pub last_heartbeat_at: Option<DateTime<Utc>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "last_assigned_at"
    )]
    pub last_assigned_at: Option<DateTime<Utc>>,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a OperatorProfile
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateOperatorProfileDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "user_id")]
    pub user_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "display_name"
    )]
    pub display_name: Option<String>,
    pub languages: Vec<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "last_heartbeat_at"
    )]
    pub last_heartbeat_at: Option<DateTime<Utc>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "last_assigned_at"
    )]
    pub last_assigned_at: Option<DateTime<Utc>>,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a OperatorProfile
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchOperatorProfileDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(skip_serializing_if = "Option::is_none", alias = "user_id")]
    pub user_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "display_name")]
    pub display_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub languages: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "last_heartbeat_at")]
    pub last_heartbeat_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "last_assigned_at")]
    pub last_assigned_at: Option<DateTime<Utc>>,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
}

impl PatchOperatorProfileDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.user_id.is_some()
            || self.display_name.is_some()
            || self.languages.is_some()
            || self.last_heartbeat_at.is_some()
            || self.last_assigned_at.is_some()
            || self.company_id.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for OperatorProfile entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct OperatorProfileResponseDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub user_id: Uuid,
    pub display_name: Option<String>,
    pub languages: Vec<String>,
    pub last_heartbeat_at: Option<DateTime<Utc>>,
    pub last_assigned_at: Option<DateTime<Utc>>,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub company_id: Uuid,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for OperatorProfile entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct OperatorProfileListResponseDto {
    /// List of items
    pub items: Vec<OperatorProfileResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl OperatorProfileListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(
        items: Vec<OperatorProfileResponseDto>,
        total: u64,
        page: u32,
        per_page: u32,
    ) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct OperatorProfileSummaryDto {
    pub id: Uuid,
    pub user_id: Uuid,
    pub display_name: Option<String>,
    pub languages: Vec<String>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<OperatorProfile> for OperatorProfileResponseDto {
    fn from(entity: OperatorProfile) -> Self {
        Self {
            id: entity.id,
            user_id: entity.user_id,
            display_name: entity.display_name,
            languages: entity.languages,
            last_heartbeat_at: entity.last_heartbeat_at,
            last_assigned_at: entity.last_assigned_at,
            company_id: entity.company_id,
            metadata: entity.metadata,
        }
    }
}

impl From<OperatorProfile> for OperatorProfileSummaryDto {
    fn from(entity: OperatorProfile) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            user_id: entity.user_id,
            display_name: entity.display_name,
            languages: entity.languages,
            created_at,
        }
    }
}

impl From<CreateOperatorProfileDto> for OperatorProfile {
    fn from(dto: CreateOperatorProfileDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            user_id: dto.user_id,
            display_name: dto.display_name,
            languages: dto.languages,
            last_heartbeat_at: dto.last_heartbeat_at,
            last_assigned_at: dto.last_assigned_at,
            company_id: dto.company_id,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&OperatorProfile> for OperatorProfileResponseDto {
    fn from(entity: &OperatorProfile) -> Self {
        Self {
            id: entity.id.clone(),
            user_id: entity.user_id.clone(),
            display_name: entity.display_name.clone(),
            languages: entity.languages.clone(),
            last_heartbeat_at: entity.last_heartbeat_at.clone(),
            last_assigned_at: entity.last_assigned_at.clone(),
            company_id: entity.company_id.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateOperatorProfileDto> for OperatorProfile {
    fn from_create_dto(dto: CreateOperatorProfileDto) -> backbone_core::ServiceResult<Self> {
        Ok(OperatorProfile::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateOperatorProfileDto> for OperatorProfile {
    fn apply_update(mut self, dto: UpdateOperatorProfileDto) -> backbone_core::ServiceResult<Self> {
        self.user_id = dto.user_id;
        self.display_name = dto.display_name;
        self.languages = dto.languages;
        self.last_heartbeat_at = dto.last_heartbeat_at;
        self.last_assigned_at = dto.last_assigned_at;
        self.company_id = dto.company_id;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to OperatorProfile here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
