//! Session DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Session;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::LivechatCloseReason;
use crate::domain::entity::LivechatFailure;
use crate::domain::entity::LivechatSessionOutcome;
use crate::domain::entity::LivechatSessionStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Session
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateSessionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "channel_id")]
    pub channel_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 300)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<LivechatSessionStatus>,
    pub failure: LivechatFailure,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub outcome: Option<LivechatSessionOutcome>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "close_reason")]
    pub close_reason: Option<LivechatCloseReason>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "closed_at")]
    pub closed_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "operator_user_id")]
    pub operator_user_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "chatbot_current_step_id")]
    pub chatbot_current_step_id: Option<Uuid>,
    #[serde(alias = "expertise_names")]
    pub expertise_names: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "website_visitor_id")]
    pub website_visitor_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 2)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "visitor_country_code")]
    pub visitor_country_code: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 60)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "visitor_timezone")]
    pub visitor_timezone: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_pending_request")]
    pub is_pending_request: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "crm_lead_id")]
    pub crm_lead_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 35)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "visitor_language")]
    pub visitor_language: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "message_count")]
    pub message_count: i32,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "first_response_at")]
    pub first_response_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "last_interest_at")]
    pub last_interest_at: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "last_visitor_message_at")]
    pub last_visitor_message_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "last_operator_message_at")]
    pub last_operator_message_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_test")]
    pub is_test: bool,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "error_detail")]
    pub error_detail: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Session
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateSessionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "channel_id")]
    pub channel_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 300)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<LivechatSessionStatus>,
    pub failure: LivechatFailure,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub outcome: Option<LivechatSessionOutcome>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "close_reason")]
    pub close_reason: Option<LivechatCloseReason>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "closed_at")]
    pub closed_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "operator_user_id")]
    pub operator_user_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "chatbot_current_step_id")]
    pub chatbot_current_step_id: Option<Uuid>,
    #[serde(alias = "expertise_names")]
    pub expertise_names: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "website_visitor_id")]
    pub website_visitor_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 2)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "visitor_country_code")]
    pub visitor_country_code: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 60)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "visitor_timezone")]
    pub visitor_timezone: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_pending_request")]
    pub is_pending_request: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "crm_lead_id")]
    pub crm_lead_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 35)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "visitor_language")]
    pub visitor_language: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "message_count")]
    pub message_count: i32,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "first_response_at")]
    pub first_response_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "last_interest_at")]
    pub last_interest_at: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "last_visitor_message_at")]
    pub last_visitor_message_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "last_operator_message_at")]
    pub last_operator_message_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_test")]
    pub is_test: bool,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "error_detail")]
    pub error_detail: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Session
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchSessionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "channel_id")]
    pub channel_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 300)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<LivechatSessionStatus>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub failure: Option<LivechatFailure>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub outcome: Option<LivechatSessionOutcome>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "close_reason")]
    pub close_reason: Option<LivechatCloseReason>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "closed_at")]
    pub closed_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "operator_user_id")]
    pub operator_user_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "chatbot_current_step_id")]
    pub chatbot_current_step_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "expertise_names")]
    pub expertise_names: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "website_visitor_id")]
    pub website_visitor_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 2)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "visitor_country_code")]
    pub visitor_country_code: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 60)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "visitor_timezone")]
    pub visitor_timezone: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_pending_request")]
    pub is_pending_request: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "crm_lead_id")]
    pub crm_lead_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 35)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "visitor_language")]
    pub visitor_language: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "message_count")]
    pub message_count: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "first_response_at")]
    pub first_response_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "last_interest_at")]
    pub last_interest_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "last_visitor_message_at")]
    pub last_visitor_message_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "last_operator_message_at")]
    pub last_operator_message_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_test")]
    pub is_test: Option<bool>,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "error_detail")]
    pub error_detail: Option<String>,
}

impl PatchSessionDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.channel_id.is_some() || self.title.is_some() || self.status.is_some() || self.failure.is_some() || self.outcome.is_some() || self.close_reason.is_some() || self.closed_at.is_some() || self.operator_user_id.is_some() || self.chatbot_current_step_id.is_some() || self.expertise_names.is_some() || self.website_visitor_id.is_some() || self.visitor_country_code.is_some() || self.visitor_timezone.is_some() || self.is_pending_request.is_some() || self.crm_lead_id.is_some() || self.visitor_language.is_some() || self.message_count.is_some() || self.first_response_at.is_some() || self.last_interest_at.is_some() || self.last_visitor_message_at.is_some() || self.last_operator_message_at.is_some() || self.is_test.is_some() || self.error_detail.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Session entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SessionResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub channel_id: Uuid,
    pub title: Option<String>,
    pub status: Option<LivechatSessionStatus>,
    pub failure: LivechatFailure,
    pub outcome: Option<LivechatSessionOutcome>,
    pub close_reason: Option<LivechatCloseReason>,
    pub closed_at: Option<DateTime<Utc>>,
    pub operator_user_id: Option<Uuid>,
    pub chatbot_current_step_id: Option<Uuid>,
    pub expertise_names: Vec<String>,
    pub website_visitor_id: Option<Uuid>,
    pub visitor_country_code: Option<String>,
    pub visitor_timezone: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_pending_request: bool,
    pub crm_lead_id: Option<Uuid>,
    pub visitor_language: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub message_count: i32,
    pub first_response_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub last_interest_at: DateTime<Utc>,
    pub last_visitor_message_at: Option<DateTime<Utc>>,
    pub last_operator_message_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_test: bool,
    pub error_detail: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Session entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SessionListResponseDto {
    /// List of items
    pub items: Vec<SessionResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl SessionListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<SessionResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SessionSummaryDto {
    pub id: Uuid,
    pub channel_id: Uuid,
    pub title: Option<String>,
    pub status: Option<LivechatSessionStatus>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Session> for SessionResponseDto {
    fn from(entity: Session) -> Self {
        Self {
            id: entity.id,
            channel_id: entity.channel_id,
            title: entity.title,
            status: entity.status,
            failure: entity.failure,
            outcome: entity.outcome,
            close_reason: entity.close_reason,
            closed_at: entity.closed_at,
            operator_user_id: entity.operator_user_id,
            chatbot_current_step_id: entity.chatbot_current_step_id,
            expertise_names: entity.expertise_names,
            website_visitor_id: entity.website_visitor_id,
            visitor_country_code: entity.visitor_country_code,
            visitor_timezone: entity.visitor_timezone,
            is_pending_request: entity.is_pending_request,
            crm_lead_id: entity.crm_lead_id,
            visitor_language: entity.visitor_language,
            message_count: entity.message_count,
            first_response_at: entity.first_response_at,
            last_interest_at: entity.last_interest_at,
            last_visitor_message_at: entity.last_visitor_message_at,
            last_operator_message_at: entity.last_operator_message_at,
            is_test: entity.is_test,
            error_detail: entity.error_detail,
            metadata: entity.metadata,
        }
    }
}

impl From<Session> for SessionSummaryDto {
    fn from(entity: Session) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            channel_id: entity.channel_id,
            title: entity.title,
            status: entity.status,
            created_at,
        }
    }
}

impl From<CreateSessionDto> for Session {
    fn from(dto: CreateSessionDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            channel_id: dto.channel_id,
            title: dto.title,
            status: dto.status,
            failure: dto.failure,
            outcome: dto.outcome,
            close_reason: dto.close_reason,
            closed_at: dto.closed_at,
            operator_user_id: dto.operator_user_id,
            chatbot_current_step_id: dto.chatbot_current_step_id,
            expertise_names: dto.expertise_names,
            website_visitor_id: dto.website_visitor_id,
            visitor_country_code: dto.visitor_country_code,
            visitor_timezone: dto.visitor_timezone,
            is_pending_request: dto.is_pending_request,
            crm_lead_id: dto.crm_lead_id,
            visitor_language: dto.visitor_language,
            message_count: dto.message_count,
            first_response_at: dto.first_response_at,
            last_interest_at: dto.last_interest_at,
            last_visitor_message_at: dto.last_visitor_message_at,
            last_operator_message_at: dto.last_operator_message_at,
            is_test: dto.is_test,
            error_detail: dto.error_detail,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Session> for SessionResponseDto {
    fn from(entity: &Session) -> Self {
        Self {
            id: entity.id.clone(),
            channel_id: entity.channel_id.clone(),
            title: entity.title.clone(),
            status: entity.status.clone(),
            failure: entity.failure.clone(),
            outcome: entity.outcome.clone(),
            close_reason: entity.close_reason.clone(),
            closed_at: entity.closed_at.clone(),
            operator_user_id: entity.operator_user_id.clone(),
            chatbot_current_step_id: entity.chatbot_current_step_id.clone(),
            expertise_names: entity.expertise_names.clone(),
            website_visitor_id: entity.website_visitor_id.clone(),
            visitor_country_code: entity.visitor_country_code.clone(),
            visitor_timezone: entity.visitor_timezone.clone(),
            is_pending_request: entity.is_pending_request.clone(),
            crm_lead_id: entity.crm_lead_id.clone(),
            visitor_language: entity.visitor_language.clone(),
            message_count: entity.message_count.clone(),
            first_response_at: entity.first_response_at.clone(),
            last_interest_at: entity.last_interest_at.clone(),
            last_visitor_message_at: entity.last_visitor_message_at.clone(),
            last_operator_message_at: entity.last_operator_message_at.clone(),
            is_test: entity.is_test.clone(),
            error_detail: entity.error_detail.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateSessionDto> for Session {
    fn from_create_dto(dto: CreateSessionDto) -> backbone_core::ServiceResult<Self> {
        Ok(Session::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateSessionDto> for Session {
    fn apply_update(mut self, dto: UpdateSessionDto) -> backbone_core::ServiceResult<Self> {
        self.channel_id = dto.channel_id;
        self.title = dto.title;
        self.status = dto.status;
        self.failure = dto.failure;
        self.outcome = dto.outcome;
        self.close_reason = dto.close_reason;
        self.closed_at = dto.closed_at;
        self.operator_user_id = dto.operator_user_id;
        self.chatbot_current_step_id = dto.chatbot_current_step_id;
        self.expertise_names = dto.expertise_names;
        self.website_visitor_id = dto.website_visitor_id;
        self.visitor_country_code = dto.visitor_country_code;
        self.visitor_timezone = dto.visitor_timezone;
        self.is_pending_request = dto.is_pending_request;
        self.crm_lead_id = dto.crm_lead_id;
        self.visitor_language = dto.visitor_language;
        self.message_count = dto.message_count;
        self.first_response_at = dto.first_response_at;
        self.last_interest_at = dto.last_interest_at;
        self.last_visitor_message_at = dto.last_visitor_message_at;
        self.last_operator_message_at = dto.last_operator_message_at;
        self.is_test = dto.is_test;
        self.error_detail = dto.error_detail;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Session here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
