//! Domain specifications
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Combinators (AND/OR/NOT) come from `backbone_core::Specification`.

pub use backbone_core::{AndSpecification, NotSpecification, OrSpecification, Specification};

pub mod channel_member_specification;
pub mod channel_rule_specification;
pub mod channel_specification;
pub mod chatbot_answer_specification;
pub mod chatbot_message_specification;
pub mod chatbot_script_specification;
pub mod chatbot_step_specification;
pub mod chatbot_step_trigger_specification;
pub mod conversation_tag_specification;
pub mod expertise_tag_specification;
pub mod livechat_audit_log_specification;
pub mod member_history_specification;
pub mod operator_expertise_specification;
pub mod operator_profile_specification;
pub mod rating_specification;
pub mod session_specification;
pub mod session_tag_specification;

// <<< CUSTOM
// END CUSTOM
