//! Application service for ChatbotAnswer entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `chatbot_answer_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::domain::entity::ChatbotAnswer;
use crate::infrastructure::persistence::ChatbotAnswerRepository;
use crate::presentation::dto::{CreateChatbotAnswerDto, UpdateChatbotAnswerDto};

/// Application service for ChatbotAnswer entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `chatbot_answer_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct ChatbotAnswerServiceCustom {
///     inner: Arc<ChatbotAnswerService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type ChatbotAnswerService = GenericCrudService<
    ChatbotAnswer,
    CreateChatbotAnswerDto,
    UpdateChatbotAnswerDto,
    ChatbotAnswerRepository,
>;

// <<< CUSTOM
// END CUSTOM
