//! Application service for ChatbotStepTrigger entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `chatbot_step_trigger_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateChatbotStepTriggerDto, UpdateChatbotStepTriggerDto};
use crate::domain::entity::ChatbotStepTrigger;
use crate::infrastructure::persistence::ChatbotStepTriggerRepository;

/// Application service for ChatbotStepTrigger entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `chatbot_step_trigger_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct ChatbotStepTriggerServiceCustom {
///     inner: Arc<ChatbotStepTriggerService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type ChatbotStepTriggerService = GenericCrudService<
    ChatbotStepTrigger,
    CreateChatbotStepTriggerDto,
    UpdateChatbotStepTriggerDto,
    ChatbotStepTriggerRepository,
>;

// <<< CUSTOM
// END CUSTOM
