//! Application service for ChatbotMessage entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `chatbot_message_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::domain::entity::ChatbotMessage;
use crate::infrastructure::persistence::ChatbotMessageRepository;
use crate::presentation::dto::{CreateChatbotMessageDto, UpdateChatbotMessageDto};

/// Application service for ChatbotMessage entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `chatbot_message_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct ChatbotMessageServiceCustom {
///     inner: Arc<ChatbotMessageService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type ChatbotMessageService = GenericCrudService<
    ChatbotMessage,
    CreateChatbotMessageDto,
    UpdateChatbotMessageDto,
    ChatbotMessageRepository,
>;

// <<< CUSTOM
// END CUSTOM
