//! Application service for ChatbotScript entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `chatbot_script_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateChatbotScriptDto, UpdateChatbotScriptDto};
use crate::domain::entity::ChatbotScript;
use crate::infrastructure::persistence::ChatbotScriptRepository;

/// Application service for ChatbotScript entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `chatbot_script_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct ChatbotScriptServiceCustom {
///     inner: Arc<ChatbotScriptService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type ChatbotScriptService = GenericCrudService<
    ChatbotScript,
    CreateChatbotScriptDto,
    UpdateChatbotScriptDto,
    ChatbotScriptRepository,
>;

// <<< CUSTOM
// END CUSTOM
