//! Application service for ChatbotStep entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `chatbot_step_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::domain::entity::ChatbotStep;
use crate::infrastructure::persistence::ChatbotStepRepository;
use crate::presentation::dto::{CreateChatbotStepDto, UpdateChatbotStepDto};

/// Application service for ChatbotStep entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `chatbot_step_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct ChatbotStepServiceCustom {
///     inner: Arc<ChatbotStepService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type ChatbotStepService = GenericCrudService<
    ChatbotStep,
    CreateChatbotStepDto,
    UpdateChatbotStepDto,
    ChatbotStepRepository,
>;

// <<< CUSTOM
// END CUSTOM
