//! Application service for LivechatAuditLog entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `livechat_audit_log_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateLivechatAuditLogDto, UpdateLivechatAuditLogDto};
use crate::domain::entity::LivechatAuditLog;
use crate::infrastructure::persistence::LivechatAuditLogRepository;

/// Application service for LivechatAuditLog entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `livechat_audit_log_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct LivechatAuditLogServiceCustom {
///     inner: Arc<LivechatAuditLogService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type LivechatAuditLogService = GenericCrudService<
    LivechatAuditLog,
    CreateLivechatAuditLogDto,
    UpdateLivechatAuditLogDto,
    LivechatAuditLogRepository,
>;

// <<< CUSTOM
// END CUSTOM
