//! Application service for MemberHistory entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `member_history_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateMemberHistoryDto, UpdateMemberHistoryDto};
use crate::domain::entity::MemberHistory;
use crate::infrastructure::persistence::MemberHistoryRepository;

/// Application service for MemberHistory entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `member_history_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct MemberHistoryServiceCustom {
///     inner: Arc<MemberHistoryService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type MemberHistoryService = GenericCrudService<
    MemberHistory,
    CreateMemberHistoryDto,
    UpdateMemberHistoryDto,
    MemberHistoryRepository,
>;

// <<< CUSTOM
// END CUSTOM
