//! Application service for OperatorProfile entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `operator_profile_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::domain::entity::OperatorProfile;
use crate::infrastructure::persistence::OperatorProfileRepository;
use crate::presentation::dto::{CreateOperatorProfileDto, UpdateOperatorProfileDto};

/// Application service for OperatorProfile entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `operator_profile_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct OperatorProfileServiceCustom {
///     inner: Arc<OperatorProfileService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type OperatorProfileService = GenericCrudService<
    OperatorProfile,
    CreateOperatorProfileDto,
    UpdateOperatorProfileDto,
    OperatorProfileRepository,
>;

// <<< CUSTOM
// END CUSTOM
