//! Application service for OperatorExpertise entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `operator_expertise_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::domain::entity::OperatorExpertise;
use crate::infrastructure::persistence::OperatorExpertiseRepository;
use crate::presentation::dto::{CreateOperatorExpertiseDto, UpdateOperatorExpertiseDto};

/// Application service for OperatorExpertise entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `operator_expertise_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct OperatorExpertiseServiceCustom {
///     inner: Arc<OperatorExpertiseService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type OperatorExpertiseService = GenericCrudService<
    OperatorExpertise,
    CreateOperatorExpertiseDto,
    UpdateOperatorExpertiseDto,
    OperatorExpertiseRepository,
>;

// <<< CUSTOM
// END CUSTOM
