//! Application service for SessionTag entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `session_tag_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateSessionTagDto, UpdateSessionTagDto};
use crate::domain::entity::SessionTag;
use crate::infrastructure::persistence::SessionTagRepository;

/// Application service for SessionTag entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `session_tag_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct SessionTagServiceCustom {
///     inner: Arc<SessionTagService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type SessionTagService = GenericCrudService<
    SessionTag,
    CreateSessionTagDto,
    UpdateSessionTagDto,
    SessionTagRepository,
>;

// <<< CUSTOM
// END CUSTOM
