-- ChannelMember Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the livechat.channel_members table.
-- Customize this file to add your initial data.

-- INSERT INTO livechat.channel_members (
--     id,
--     channel_id,
--     user_id,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO livechat.channel_members (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

