-- ChatbotAnswer Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the livechat.chatbot_answers table.
-- Customize this file to add your initial data.

-- INSERT INTO livechat.chatbot_answers (
--     id,
--     question_step_id,
--     sequence,
--     label,
--     redirect_url,
--     company_id,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO livechat.chatbot_answers (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

