-- ChatbotMessage Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the livechat.chatbot_messages table.
-- Customize this file to add your initial data.

-- INSERT INTO livechat.chatbot_messages (
--     id,
--     session_id,
--     step_id,
--     carrier_message_id,
--     selected_answer_id,
--     visitor_answer,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO livechat.chatbot_messages (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

