-- ChatbotStep Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the livechat.chatbot_steps table.
-- Customize this file to add your initial data.

-- INSERT INTO livechat.chatbot_steps (
--     id,
--     chatbot_script_id,
--     sequence,
--     step_type,
--     message,
--     expertise_tag_ids,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO livechat.chatbot_steps (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

