-- MemberHistory Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the livechat.member_histories table.
-- Customize this file to add your initial data.

-- INSERT INTO livechat.member_histories (
--     id,
--     session_id,
--     persona,
--     operator_user_id,
--     visitor_key,
--     chatbot_script_id,
--     joined_at,
--     left_at,
--     message_count,
--     response_time_secs,
--     expertise_names,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO livechat.member_histories (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

