-- OperatorProfile Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the livechat.operator_profiles table.
-- Customize this file to add your initial data.

-- INSERT INTO livechat.operator_profiles (
--     id,
--     user_id,
--     display_name,
--     languages,
--     last_heartbeat_at,
--     last_assigned_at,
--     company_id,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO livechat.operator_profiles (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

