-- Rating Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the livechat.ratings table.
-- Customize this file to add your initial data.

-- INSERT INTO livechat.ratings (
--     id,
--     session_id,
--     value,
--     rated_persona,
--     operator_user_id,
--     chatbot_script_id,
--     comment,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO livechat.ratings (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

