-- Session Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the livechat.sessions table.
-- Customize this file to add your initial data.

-- INSERT INTO livechat.sessions (
--     id,
--     channel_id,
--     title,
--     status,
--     failure,
--     outcome,
--     close_reason,
--     closed_at,
--     operator_user_id,
--     chatbot_current_step_id,
--     expertise_names,
--     website_visitor_id,
--     visitor_country_code,
--     visitor_timezone,
--     is_pending_request,
--     visitor_language,
--     message_count,
--     first_response_at,
--     last_interest_at,
--     last_visitor_message_at,
--     last_operator_message_at,
--     is_test,
--     error_detail,
--     company_id,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO livechat.sessions (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

