-- Migration: Create session_tags table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS livechat;

CREATE TABLE IF NOT EXISTS livechat.session_tags (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    session_id UUID NOT NULL,
    tag_id UUID NOT NULL,
    company_id UUID NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_session_tags_metadata_gin ON livechat.session_tags USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_session_tags_metadata_deleted_at ON livechat.session_tags ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_session_tags_metadata_created_at ON livechat.session_tags ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_session_tags_metadata_updated_at ON livechat.session_tags ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION livechat.session_tags_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS session_tags_insert_audit ON livechat.session_tags;
CREATE TRIGGER session_tags_insert_audit BEFORE INSERT ON livechat.session_tags
    FOR EACH ROW EXECUTE FUNCTION livechat.session_tags_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS session_tags_update_audit ON livechat.session_tags;
CREATE TRIGGER session_tags_update_audit BEFORE UPDATE ON livechat.session_tags
    FOR EACH ROW EXECUTE FUNCTION livechat.session_tags_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE livechat.session_tags ADD CONSTRAINT fk_session_tags_session_id FOREIGN KEY (session_id) REFERENCES livechat.sessions (id);
ALTER TABLE livechat.session_tags ADD CONSTRAINT fk_session_tags_tag_id FOREIGN KEY (tag_id) REFERENCES livechat.conversation_tags (id);
