-- Migration: Create ratings table
-- Generated by metaphor-schema

-- Create livechat_rated_persona enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'livechat_rated_persona') THEN
        CREATE TYPE livechat_rated_persona AS ENUM ('agent', 'bot');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS livechat;

CREATE TABLE IF NOT EXISTS livechat.ratings (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    session_id UUID NOT NULL,
    value INTEGER NOT NULL,
    rated_persona livechat_rated_persona NOT NULL DEFAULT 'agent',
    operator_user_id UUID,
    chatbot_script_id UUID,
    comment TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    company_id UUID NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_ratings_session_id ON livechat.ratings (session_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_ratings_metadata_gin ON livechat.ratings USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_ratings_metadata_deleted_at ON livechat.ratings ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_ratings_metadata_created_at ON livechat.ratings ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_ratings_metadata_updated_at ON livechat.ratings ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION livechat.ratings_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS ratings_insert_audit ON livechat.ratings;
CREATE TRIGGER ratings_insert_audit BEFORE INSERT ON livechat.ratings
    FOR EACH ROW EXECUTE FUNCTION livechat.ratings_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS ratings_update_audit ON livechat.ratings;
CREATE TRIGGER ratings_update_audit BEFORE UPDATE ON livechat.ratings
    FOR EACH ROW EXECUTE FUNCTION livechat.ratings_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE livechat.ratings ADD CONSTRAINT fk_ratings_session_id FOREIGN KEY (session_id) REFERENCES livechat.sessions (id);
