-- Migration: Create chatbot_step_triggers table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS livechat;

CREATE TABLE IF NOT EXISTS livechat.chatbot_step_triggers (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    answer_id UUID NOT NULL,
    target_step_id UUID NOT NULL,
    company_id UUID NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_chatbot_step_triggers_metadata_gin ON livechat.chatbot_step_triggers USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_chatbot_step_triggers_metadata_deleted_at ON livechat.chatbot_step_triggers ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_chatbot_step_triggers_metadata_created_at ON livechat.chatbot_step_triggers ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_chatbot_step_triggers_metadata_updated_at ON livechat.chatbot_step_triggers ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION livechat.chatbot_step_triggers_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS chatbot_step_triggers_insert_audit ON livechat.chatbot_step_triggers;
CREATE TRIGGER chatbot_step_triggers_insert_audit BEFORE INSERT ON livechat.chatbot_step_triggers
    FOR EACH ROW EXECUTE FUNCTION livechat.chatbot_step_triggers_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS chatbot_step_triggers_update_audit ON livechat.chatbot_step_triggers;
CREATE TRIGGER chatbot_step_triggers_update_audit BEFORE UPDATE ON livechat.chatbot_step_triggers
    FOR EACH ROW EXECUTE FUNCTION livechat.chatbot_step_triggers_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE livechat.chatbot_step_triggers ADD CONSTRAINT fk_chatbot_step_triggers_answer_id FOREIGN KEY (answer_id) REFERENCES livechat.chatbot_answers (id);
ALTER TABLE livechat.chatbot_step_triggers ADD CONSTRAINT fk_chatbot_step_triggers_target_step_id FOREIGN KEY (target_step_id) REFERENCES livechat.chatbot_steps (id);
