-- Migration: Create channel_members table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS livechat;

CREATE TABLE IF NOT EXISTS livechat.channel_members (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    channel_id UUID NOT NULL,
    user_id UUID NOT NULL,
    company_id UUID NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_channel_members_channel_id_user_id ON livechat.channel_members (channel_id, user_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_channel_members_metadata_gin ON livechat.channel_members USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_channel_members_metadata_deleted_at ON livechat.channel_members ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_channel_members_metadata_created_at ON livechat.channel_members ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_channel_members_metadata_updated_at ON livechat.channel_members ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION livechat.channel_members_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS channel_members_insert_audit ON livechat.channel_members;
CREATE TRIGGER channel_members_insert_audit BEFORE INSERT ON livechat.channel_members
    FOR EACH ROW EXECUTE FUNCTION livechat.channel_members_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS channel_members_update_audit ON livechat.channel_members;
CREATE TRIGGER channel_members_update_audit BEFORE UPDATE ON livechat.channel_members
    FOR EACH ROW EXECUTE FUNCTION livechat.channel_members_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE livechat.channel_members ADD CONSTRAINT fk_channel_members_channel_id FOREIGN KEY (channel_id) REFERENCES livechat.channels (id);
