-- Migration: Create sessions table
-- Generated by metaphor-schema

-- Create livechat_session_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'livechat_session_status') THEN
        CREATE TYPE livechat_session_status AS ENUM ('waiting', 'in_progress', 'need_help');
    END IF;
END
$$;

-- Create livechat_failure enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'livechat_failure') THEN
        CREATE TYPE livechat_failure AS ENUM ('no_answer', 'no_agent', 'no_failure');
    END IF;
END
$$;

-- Create livechat_session_outcome enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'livechat_session_outcome') THEN
        CREATE TYPE livechat_session_outcome AS ENUM ('no_failure', 'no_answer', 'no_agent', 'escalated');
    END IF;
END
$$;

-- Create livechat_close_reason enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'livechat_close_reason') THEN
        CREATE TYPE livechat_close_reason AS ENUM ('visitor_left', 'operator_closed', 'bot_completed', 'expired', 'cancelled', 'request_declined');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS livechat;

CREATE TABLE IF NOT EXISTS livechat.sessions (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    channel_id UUID NOT NULL,
    title TEXT,
    status livechat_session_status DEFAULT 'waiting',
    failure livechat_failure NOT NULL DEFAULT 'no_failure',
    outcome livechat_session_outcome,
    close_reason livechat_close_reason,
    closed_at TIMESTAMPTZ,
    operator_user_id UUID,
    chatbot_current_step_id UUID,
    expertise_names TEXT[] NOT NULL,
    website_visitor_id UUID,
    visitor_country_code TEXT,
    visitor_timezone TEXT,
    is_pending_request BOOLEAN NOT NULL DEFAULT FALSE,
    visitor_language TEXT,
    message_count INTEGER NOT NULL DEFAULT 0 CHECK (message_count >= 0),
    first_response_at TIMESTAMPTZ,
    last_interest_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_visitor_message_at TIMESTAMPTZ,
    last_operator_message_at TIMESTAMPTZ,
    is_test BOOLEAN NOT NULL DEFAULT FALSE,
    error_detail TEXT,
    company_id UUID NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_sessions_metadata_gin ON livechat.sessions USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_sessions_metadata_deleted_at ON livechat.sessions ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_sessions_metadata_created_at ON livechat.sessions ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_sessions_metadata_updated_at ON livechat.sessions ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION livechat.sessions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS sessions_insert_audit ON livechat.sessions;
CREATE TRIGGER sessions_insert_audit BEFORE INSERT ON livechat.sessions
    FOR EACH ROW EXECUTE FUNCTION livechat.sessions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS sessions_update_audit ON livechat.sessions;
CREATE TRIGGER sessions_update_audit BEFORE UPDATE ON livechat.sessions
    FOR EACH ROW EXECUTE FUNCTION livechat.sessions_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE livechat.sessions ADD CONSTRAINT fk_sessions_channel_id FOREIGN KEY (channel_id) REFERENCES livechat.channels (id);
