-- Audit Triggers Migration for livechat module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: Channel (livechat.channels)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION livechat.channels_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS channels_insert_audit ON livechat.channels;
CREATE TRIGGER channels_insert_audit BEFORE INSERT ON livechat.channels
    FOR EACH ROW EXECUTE FUNCTION livechat.channels_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS channels_update_audit ON livechat.channels;
CREATE TRIGGER channels_update_audit BEFORE UPDATE ON livechat.channels
    FOR EACH ROW EXECUTE FUNCTION livechat.channels_audit_timestamp();

-- ==============================================================================
-- Table: ChannelMember (livechat.channel_members)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION livechat.channel_members_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS channel_members_insert_audit ON livechat.channel_members;
CREATE TRIGGER channel_members_insert_audit BEFORE INSERT ON livechat.channel_members
    FOR EACH ROW EXECUTE FUNCTION livechat.channel_members_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS channel_members_update_audit ON livechat.channel_members;
CREATE TRIGGER channel_members_update_audit BEFORE UPDATE ON livechat.channel_members
    FOR EACH ROW EXECUTE FUNCTION livechat.channel_members_audit_timestamp();

-- ==============================================================================
-- Table: ChannelRule (livechat.channel_rules)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION livechat.channel_rules_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS channel_rules_insert_audit ON livechat.channel_rules;
CREATE TRIGGER channel_rules_insert_audit BEFORE INSERT ON livechat.channel_rules
    FOR EACH ROW EXECUTE FUNCTION livechat.channel_rules_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS channel_rules_update_audit ON livechat.channel_rules;
CREATE TRIGGER channel_rules_update_audit BEFORE UPDATE ON livechat.channel_rules
    FOR EACH ROW EXECUTE FUNCTION livechat.channel_rules_audit_timestamp();

-- ==============================================================================
-- Table: ChatbotAnswer (livechat.chatbot_answers)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION livechat.chatbot_answers_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS chatbot_answers_insert_audit ON livechat.chatbot_answers;
CREATE TRIGGER chatbot_answers_insert_audit BEFORE INSERT ON livechat.chatbot_answers
    FOR EACH ROW EXECUTE FUNCTION livechat.chatbot_answers_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS chatbot_answers_update_audit ON livechat.chatbot_answers;
CREATE TRIGGER chatbot_answers_update_audit BEFORE UPDATE ON livechat.chatbot_answers
    FOR EACH ROW EXECUTE FUNCTION livechat.chatbot_answers_audit_timestamp();

-- ==============================================================================
-- Table: ChatbotMessage (livechat.chatbot_messages)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION livechat.chatbot_messages_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS chatbot_messages_insert_audit ON livechat.chatbot_messages;
CREATE TRIGGER chatbot_messages_insert_audit BEFORE INSERT ON livechat.chatbot_messages
    FOR EACH ROW EXECUTE FUNCTION livechat.chatbot_messages_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS chatbot_messages_update_audit ON livechat.chatbot_messages;
CREATE TRIGGER chatbot_messages_update_audit BEFORE UPDATE ON livechat.chatbot_messages
    FOR EACH ROW EXECUTE FUNCTION livechat.chatbot_messages_audit_timestamp();

-- ==============================================================================
-- Table: ChatbotScript (livechat.chatbot_scripts)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION livechat.chatbot_scripts_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS chatbot_scripts_insert_audit ON livechat.chatbot_scripts;
CREATE TRIGGER chatbot_scripts_insert_audit BEFORE INSERT ON livechat.chatbot_scripts
    FOR EACH ROW EXECUTE FUNCTION livechat.chatbot_scripts_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS chatbot_scripts_update_audit ON livechat.chatbot_scripts;
CREATE TRIGGER chatbot_scripts_update_audit BEFORE UPDATE ON livechat.chatbot_scripts
    FOR EACH ROW EXECUTE FUNCTION livechat.chatbot_scripts_audit_timestamp();

-- ==============================================================================
-- Table: ChatbotStep (livechat.chatbot_steps)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION livechat.chatbot_steps_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS chatbot_steps_insert_audit ON livechat.chatbot_steps;
CREATE TRIGGER chatbot_steps_insert_audit BEFORE INSERT ON livechat.chatbot_steps
    FOR EACH ROW EXECUTE FUNCTION livechat.chatbot_steps_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS chatbot_steps_update_audit ON livechat.chatbot_steps;
CREATE TRIGGER chatbot_steps_update_audit BEFORE UPDATE ON livechat.chatbot_steps
    FOR EACH ROW EXECUTE FUNCTION livechat.chatbot_steps_audit_timestamp();

-- ==============================================================================
-- Table: ChatbotStepTrigger (livechat.chatbot_step_triggers)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION livechat.chatbot_step_triggers_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS chatbot_step_triggers_insert_audit ON livechat.chatbot_step_triggers;
CREATE TRIGGER chatbot_step_triggers_insert_audit BEFORE INSERT ON livechat.chatbot_step_triggers
    FOR EACH ROW EXECUTE FUNCTION livechat.chatbot_step_triggers_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS chatbot_step_triggers_update_audit ON livechat.chatbot_step_triggers;
CREATE TRIGGER chatbot_step_triggers_update_audit BEFORE UPDATE ON livechat.chatbot_step_triggers
    FOR EACH ROW EXECUTE FUNCTION livechat.chatbot_step_triggers_audit_timestamp();

-- ==============================================================================
-- Table: ConversationTag (livechat.conversation_tags)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION livechat.conversation_tags_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS conversation_tags_insert_audit ON livechat.conversation_tags;
CREATE TRIGGER conversation_tags_insert_audit BEFORE INSERT ON livechat.conversation_tags
    FOR EACH ROW EXECUTE FUNCTION livechat.conversation_tags_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS conversation_tags_update_audit ON livechat.conversation_tags;
CREATE TRIGGER conversation_tags_update_audit BEFORE UPDATE ON livechat.conversation_tags
    FOR EACH ROW EXECUTE FUNCTION livechat.conversation_tags_audit_timestamp();

-- ==============================================================================
-- Table: ExpertiseTag (livechat.expertise_tags)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION livechat.expertise_tags_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS expertise_tags_insert_audit ON livechat.expertise_tags;
CREATE TRIGGER expertise_tags_insert_audit BEFORE INSERT ON livechat.expertise_tags
    FOR EACH ROW EXECUTE FUNCTION livechat.expertise_tags_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS expertise_tags_update_audit ON livechat.expertise_tags;
CREATE TRIGGER expertise_tags_update_audit BEFORE UPDATE ON livechat.expertise_tags
    FOR EACH ROW EXECUTE FUNCTION livechat.expertise_tags_audit_timestamp();

-- ==============================================================================
-- Table: LivechatAuditLog (livechat.livechat_audit_log)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION livechat.livechat_audit_log_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS livechat_audit_log_insert_audit ON livechat.livechat_audit_log;
CREATE TRIGGER livechat_audit_log_insert_audit BEFORE INSERT ON livechat.livechat_audit_log
    FOR EACH ROW EXECUTE FUNCTION livechat.livechat_audit_log_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS livechat_audit_log_update_audit ON livechat.livechat_audit_log;
CREATE TRIGGER livechat_audit_log_update_audit BEFORE UPDATE ON livechat.livechat_audit_log
    FOR EACH ROW EXECUTE FUNCTION livechat.livechat_audit_log_audit_timestamp();

-- ==============================================================================
-- Table: MemberHistory (livechat.member_histories)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION livechat.member_histories_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS member_histories_insert_audit ON livechat.member_histories;
CREATE TRIGGER member_histories_insert_audit BEFORE INSERT ON livechat.member_histories
    FOR EACH ROW EXECUTE FUNCTION livechat.member_histories_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS member_histories_update_audit ON livechat.member_histories;
CREATE TRIGGER member_histories_update_audit BEFORE UPDATE ON livechat.member_histories
    FOR EACH ROW EXECUTE FUNCTION livechat.member_histories_audit_timestamp();

-- ==============================================================================
-- Table: OperatorExpertise (livechat.operator_expertise)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION livechat.operator_expertise_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS operator_expertise_insert_audit ON livechat.operator_expertise;
CREATE TRIGGER operator_expertise_insert_audit BEFORE INSERT ON livechat.operator_expertise
    FOR EACH ROW EXECUTE FUNCTION livechat.operator_expertise_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS operator_expertise_update_audit ON livechat.operator_expertise;
CREATE TRIGGER operator_expertise_update_audit BEFORE UPDATE ON livechat.operator_expertise
    FOR EACH ROW EXECUTE FUNCTION livechat.operator_expertise_audit_timestamp();

-- ==============================================================================
-- Table: OperatorProfile (livechat.operator_profiles)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION livechat.operator_profiles_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS operator_profiles_insert_audit ON livechat.operator_profiles;
CREATE TRIGGER operator_profiles_insert_audit BEFORE INSERT ON livechat.operator_profiles
    FOR EACH ROW EXECUTE FUNCTION livechat.operator_profiles_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS operator_profiles_update_audit ON livechat.operator_profiles;
CREATE TRIGGER operator_profiles_update_audit BEFORE UPDATE ON livechat.operator_profiles
    FOR EACH ROW EXECUTE FUNCTION livechat.operator_profiles_audit_timestamp();

-- ==============================================================================
-- Table: Rating (livechat.ratings)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION livechat.ratings_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS ratings_insert_audit ON livechat.ratings;
CREATE TRIGGER ratings_insert_audit BEFORE INSERT ON livechat.ratings
    FOR EACH ROW EXECUTE FUNCTION livechat.ratings_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS ratings_update_audit ON livechat.ratings;
CREATE TRIGGER ratings_update_audit BEFORE UPDATE ON livechat.ratings
    FOR EACH ROW EXECUTE FUNCTION livechat.ratings_audit_timestamp();

-- ==============================================================================
-- Table: Session (livechat.sessions)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION livechat.sessions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS sessions_insert_audit ON livechat.sessions;
CREATE TRIGGER sessions_insert_audit BEFORE INSERT ON livechat.sessions
    FOR EACH ROW EXECUTE FUNCTION livechat.sessions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS sessions_update_audit ON livechat.sessions;
CREATE TRIGGER sessions_update_audit BEFORE UPDATE ON livechat.sessions
    FOR EACH ROW EXECUTE FUNCTION livechat.sessions_audit_timestamp();

-- ==============================================================================
-- Table: SessionTag (livechat.session_tags)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION livechat.session_tags_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS session_tags_insert_audit ON livechat.session_tags;
CREATE TRIGGER session_tags_insert_audit BEFORE INSERT ON livechat.session_tags
    FOR EACH ROW EXECUTE FUNCTION livechat.session_tags_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS session_tags_update_audit ON livechat.session_tags;
CREATE TRIGGER session_tags_update_audit BEFORE UPDATE ON livechat.session_tags
    FOR EACH ROW EXECUTE FUNCTION livechat.session_tags_audit_timestamp();

