-- Migration: Create chatbot_steps table
-- Generated by metaphor-schema

-- Create livechat_step_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'livechat_step_type') THEN
        CREATE TYPE livechat_step_type AS ENUM ('text', 'question_selection', 'question_email', 'question_phone', 'forward_operator', 'free_input_single', 'free_input_multi');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS livechat;

CREATE TABLE IF NOT EXISTS livechat.chatbot_steps (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    chatbot_script_id UUID NOT NULL,
    sequence INTEGER NOT NULL CHECK (sequence >= 0),
    step_type livechat_step_type NOT NULL DEFAULT 'text',
    message TEXT,
    expertise_tag_ids UUID[] NOT NULL,
    company_id UUID NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_chatbot_steps_metadata_gin ON livechat.chatbot_steps USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_chatbot_steps_metadata_deleted_at ON livechat.chatbot_steps ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_chatbot_steps_metadata_created_at ON livechat.chatbot_steps ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_chatbot_steps_metadata_updated_at ON livechat.chatbot_steps ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION livechat.chatbot_steps_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS chatbot_steps_insert_audit ON livechat.chatbot_steps;
CREATE TRIGGER chatbot_steps_insert_audit BEFORE INSERT ON livechat.chatbot_steps
    FOR EACH ROW EXECUTE FUNCTION livechat.chatbot_steps_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS chatbot_steps_update_audit ON livechat.chatbot_steps;
CREATE TRIGGER chatbot_steps_update_audit BEFORE UPDATE ON livechat.chatbot_steps
    FOR EACH ROW EXECUTE FUNCTION livechat.chatbot_steps_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE livechat.chatbot_steps ADD CONSTRAINT fk_chatbot_steps_chatbot_script_id FOREIGN KEY (chatbot_script_id) REFERENCES livechat.chatbot_scripts (id);
