-- Company RLS fence for livechat module (ADR-0008)
-- Generated by metaphor-schema. Requires the app to connect as a
-- non-superuser role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for livechat.channels
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE livechat.channels ENABLE ROW LEVEL SECURITY;
ALTER TABLE livechat.channels FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS channels_company_isolation ON livechat.channels;
CREATE POLICY channels_company_isolation ON livechat.channels
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for livechat.channel_members
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE livechat.channel_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE livechat.channel_members FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS channel_members_company_isolation ON livechat.channel_members;
CREATE POLICY channel_members_company_isolation ON livechat.channel_members
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for livechat.channel_rules
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE livechat.channel_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE livechat.channel_rules FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS channel_rules_company_isolation ON livechat.channel_rules;
CREATE POLICY channel_rules_company_isolation ON livechat.channel_rules
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for livechat.chatbot_answers
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE livechat.chatbot_answers ENABLE ROW LEVEL SECURITY;
ALTER TABLE livechat.chatbot_answers FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS chatbot_answers_company_isolation ON livechat.chatbot_answers;
CREATE POLICY chatbot_answers_company_isolation ON livechat.chatbot_answers
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for livechat.chatbot_messages
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE livechat.chatbot_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE livechat.chatbot_messages FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS chatbot_messages_company_isolation ON livechat.chatbot_messages;
CREATE POLICY chatbot_messages_company_isolation ON livechat.chatbot_messages
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for livechat.chatbot_scripts
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE livechat.chatbot_scripts ENABLE ROW LEVEL SECURITY;
ALTER TABLE livechat.chatbot_scripts FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS chatbot_scripts_company_isolation ON livechat.chatbot_scripts;
CREATE POLICY chatbot_scripts_company_isolation ON livechat.chatbot_scripts
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for livechat.chatbot_steps
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE livechat.chatbot_steps ENABLE ROW LEVEL SECURITY;
ALTER TABLE livechat.chatbot_steps FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS chatbot_steps_company_isolation ON livechat.chatbot_steps;
CREATE POLICY chatbot_steps_company_isolation ON livechat.chatbot_steps
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for livechat.chatbot_step_triggers
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE livechat.chatbot_step_triggers ENABLE ROW LEVEL SECURITY;
ALTER TABLE livechat.chatbot_step_triggers FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS chatbot_step_triggers_company_isolation ON livechat.chatbot_step_triggers;
CREATE POLICY chatbot_step_triggers_company_isolation ON livechat.chatbot_step_triggers
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for livechat.conversation_tags
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE livechat.conversation_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE livechat.conversation_tags FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS conversation_tags_company_isolation ON livechat.conversation_tags;
CREATE POLICY conversation_tags_company_isolation ON livechat.conversation_tags
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for livechat.expertise_tags
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE livechat.expertise_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE livechat.expertise_tags FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS expertise_tags_company_isolation ON livechat.expertise_tags;
CREATE POLICY expertise_tags_company_isolation ON livechat.expertise_tags
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for livechat.livechat_audit_log
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE livechat.livechat_audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE livechat.livechat_audit_log FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS livechat_audit_log_company_isolation ON livechat.livechat_audit_log;
CREATE POLICY livechat_audit_log_company_isolation ON livechat.livechat_audit_log
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for livechat.member_histories
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE livechat.member_histories ENABLE ROW LEVEL SECURITY;
ALTER TABLE livechat.member_histories FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS member_histories_company_isolation ON livechat.member_histories;
CREATE POLICY member_histories_company_isolation ON livechat.member_histories
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for livechat.operator_expertise
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE livechat.operator_expertise ENABLE ROW LEVEL SECURITY;
ALTER TABLE livechat.operator_expertise FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS operator_expertise_company_isolation ON livechat.operator_expertise;
CREATE POLICY operator_expertise_company_isolation ON livechat.operator_expertise
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for livechat.operator_profiles
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE livechat.operator_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE livechat.operator_profiles FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS operator_profiles_company_isolation ON livechat.operator_profiles;
CREATE POLICY operator_profiles_company_isolation ON livechat.operator_profiles
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for livechat.ratings
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE livechat.ratings ENABLE ROW LEVEL SECURITY;
ALTER TABLE livechat.ratings FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS ratings_company_isolation ON livechat.ratings;
CREATE POLICY ratings_company_isolation ON livechat.ratings
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for livechat.sessions
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE livechat.sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE livechat.sessions FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS sessions_company_isolation ON livechat.sessions;
CREATE POLICY sessions_company_isolation ON livechat.sessions
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for livechat.session_tags
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE livechat.session_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE livechat.session_tags FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS session_tags_company_isolation ON livechat.session_tags;
CREATE POLICY session_tags_company_isolation ON livechat.session_tags
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

