-- Migration: Create livechat_audit_log table
-- Generated by metaphor-schema

-- Create livechat_audit_event enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'livechat_audit_event') THEN
        CREATE TYPE livechat_audit_event AS ENUM ('session_opened', 'operator_assigned', 'operator_busy', 'assignment_empty', 'session_closed', 'session_reopened', 'session_rated', 'rating_refused', 'chatbot_step_reached', 'chatbot_restarted', 'chatbot_forwarded', 'help_requested', 'help_resolved', 'invite_created', 'invite_delivered', 'invite_cancelled', 'invite_accepted', 'invite_expired', 'visitor_relinked', 'carrier_parked', 'capability_refused', 'throttled', 'test_session_opened');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS livechat;

CREATE TABLE IF NOT EXISTS livechat.livechat_audit_log (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    event livechat_audit_event NOT NULL,
    actor UUID,
    subject_type TEXT,
    subject_id UUID,
    detail JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    company_id UUID NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_livechat_audit_log_event_created_at ON livechat.livechat_audit_log (event, created_at);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_livechat_audit_log_metadata_gin ON livechat.livechat_audit_log USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_livechat_audit_log_metadata_deleted_at ON livechat.livechat_audit_log ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_livechat_audit_log_metadata_created_at ON livechat.livechat_audit_log ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_livechat_audit_log_metadata_updated_at ON livechat.livechat_audit_log ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION livechat.livechat_audit_log_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS livechat_audit_log_insert_audit ON livechat.livechat_audit_log;
CREATE TRIGGER livechat_audit_log_insert_audit BEFORE INSERT ON livechat.livechat_audit_log
    FOR EACH ROW EXECUTE FUNCTION livechat.livechat_audit_log_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS livechat_audit_log_update_audit ON livechat.livechat_audit_log;
CREATE TRIGGER livechat_audit_log_update_audit BEFORE UPDATE ON livechat.livechat_audit_log
    FOR EACH ROW EXECUTE FUNCTION livechat.livechat_audit_log_audit_timestamp();
