-- Migration: Create operator_expertise table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS livechat;

CREATE TABLE IF NOT EXISTS livechat.operator_expertise (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    operator_profile_id UUID NOT NULL,
    expertise_tag_id UUID NOT NULL,
    company_id UUID NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_operator_expertise_metadata_gin ON livechat.operator_expertise USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_operator_expertise_metadata_deleted_at ON livechat.operator_expertise ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_operator_expertise_metadata_created_at ON livechat.operator_expertise ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_operator_expertise_metadata_updated_at ON livechat.operator_expertise ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION livechat.operator_expertise_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS operator_expertise_insert_audit ON livechat.operator_expertise;
CREATE TRIGGER operator_expertise_insert_audit BEFORE INSERT ON livechat.operator_expertise
    FOR EACH ROW EXECUTE FUNCTION livechat.operator_expertise_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS operator_expertise_update_audit ON livechat.operator_expertise;
CREATE TRIGGER operator_expertise_update_audit BEFORE UPDATE ON livechat.operator_expertise
    FOR EACH ROW EXECUTE FUNCTION livechat.operator_expertise_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE livechat.operator_expertise ADD CONSTRAINT fk_operator_expertise_operator_profile_id FOREIGN KEY (operator_profile_id) REFERENCES livechat.operator_profiles (id);
ALTER TABLE livechat.operator_expertise ADD CONSTRAINT fk_operator_expertise_expertise_tag_id FOREIGN KEY (expertise_tag_id) REFERENCES livechat.expertise_tags (id);
