//! Event handler trait for ChannelRule events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::ChannelRuleEvent;
use backbone_messaging::EventHandler;

/// Event handler for ChannelRule events.
/// Implement this trait to react to ChannelRule lifecycle events.
pub trait ChannelRuleEventHandler: EventHandler<ChannelRuleEvent> {}
