//! Event handler trait for Channel events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::ChannelEvent;
use backbone_messaging::EventHandler;

/// Event handler for Channel events.
/// Implement this trait to react to Channel lifecycle events.
pub trait ChannelEventHandler: EventHandler<ChannelEvent> {}
