//! Domain events for ChannelRule entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::ChannelRule;

/// Domain events for ChannelRule — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<ChannelRule>)` variant.
pub type ChannelRuleEvent = CrudEvent<ChannelRule>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for ChannelRule events.
pub type ChannelRuleEventPublisher = Arc<dyn CrudEventPublisher<ChannelRule> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopChannelRuleEventPublisher = NoOpCrudEventPublisher<ChannelRule>;
