//! Domain events for ChatbotStep entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use crate::domain::entity::ChatbotStep;
use backbone_messaging::CrudEvent;

/// Domain events for ChatbotStep — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<ChatbotStep>)` variant.
pub type ChatbotStepEvent = CrudEvent<ChatbotStep>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for ChatbotStep events.
pub type ChatbotStepEventPublisher = Arc<dyn CrudEventPublisher<ChatbotStep> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopChatbotStepEventPublisher = NoOpCrudEventPublisher<ChatbotStep>;
