//! Domain events for ChatbotStepTrigger entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::ChatbotStepTrigger;

/// Domain events for ChatbotStepTrigger — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<ChatbotStepTrigger>)` variant.
pub type ChatbotStepTriggerEvent = CrudEvent<ChatbotStepTrigger>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for ChatbotStepTrigger events.
pub type ChatbotStepTriggerEventPublisher = Arc<dyn CrudEventPublisher<ChatbotStepTrigger> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopChatbotStepTriggerEventPublisher = NoOpCrudEventPublisher<ChatbotStepTrigger>;
