//! Event handler trait for ChatbotMessage events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::ChatbotMessageEvent;

/// Event handler for ChatbotMessage events.
/// Implement this trait to react to ChatbotMessage lifecycle events.
pub trait ChatbotMessageEventHandler: EventHandler<ChatbotMessageEvent> {}
