//! Event handler trait for ChatbotAnswer events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::ChatbotAnswerEvent;

/// Event handler for ChatbotAnswer events.
/// Implement this trait to react to ChatbotAnswer lifecycle events.
pub trait ChatbotAnswerEventHandler: EventHandler<ChatbotAnswerEvent> {}
