//! Event handler trait for ChatbotStepTrigger events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::ChatbotStepTriggerEvent;
use backbone_messaging::EventHandler;

/// Event handler for ChatbotStepTrigger events.
/// Implement this trait to react to ChatbotStepTrigger lifecycle events.
pub trait ChatbotStepTriggerEventHandler: EventHandler<ChatbotStepTriggerEvent> {}
