//! Event handler trait for ChatbotScript events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::ChatbotScriptEvent;
use backbone_messaging::EventHandler;

/// Event handler for ChatbotScript events.
/// Implement this trait to react to ChatbotScript lifecycle events.
pub trait ChatbotScriptEventHandler: EventHandler<ChatbotScriptEvent> {}
