//! Event handler trait for ChatbotStep events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::ChatbotStepEvent;

/// Event handler for ChatbotStep events.
/// Implement this trait to react to ChatbotStep lifecycle events.
pub trait ChatbotStepEventHandler: EventHandler<ChatbotStepEvent> {}
