//! Domain events for ChatbotMessage entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use crate::domain::entity::ChatbotMessage;
use backbone_messaging::CrudEvent;

/// Domain events for ChatbotMessage — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<ChatbotMessage>)` variant.
pub type ChatbotMessageEvent = CrudEvent<ChatbotMessage>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for ChatbotMessage events.
pub type ChatbotMessageEventPublisher = Arc<dyn CrudEventPublisher<ChatbotMessage> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopChatbotMessageEventPublisher = NoOpCrudEventPublisher<ChatbotMessage>;
