//! Event handler trait for ConversationTag events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::ConversationTagEvent;
use backbone_messaging::EventHandler;

/// Event handler for ConversationTag events.
/// Implement this trait to react to ConversationTag lifecycle events.
pub trait ConversationTagEventHandler: EventHandler<ConversationTagEvent> {}
