//! Domain events for ExpertiseTag entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use crate::domain::entity::ExpertiseTag;
use backbone_messaging::CrudEvent;

/// Domain events for ExpertiseTag — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<ExpertiseTag>)` variant.
pub type ExpertiseTagEvent = CrudEvent<ExpertiseTag>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for ExpertiseTag events.
pub type ExpertiseTagEventPublisher = Arc<dyn CrudEventPublisher<ExpertiseTag> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopExpertiseTagEventPublisher = NoOpCrudEventPublisher<ExpertiseTag>;
