//! Event handler trait for ExpertiseTag events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::ExpertiseTagEvent;

/// Event handler for ExpertiseTag events.
/// Implement this trait to react to ExpertiseTag lifecycle events.
pub trait ExpertiseTagEventHandler: EventHandler<ExpertiseTagEvent> {}
