//! Domain events for LivechatAuditLog entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::LivechatAuditLog;

/// Domain events for LivechatAuditLog — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<LivechatAuditLog>)` variant.
pub type LivechatAuditLogEvent = CrudEvent<LivechatAuditLog>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for LivechatAuditLog events.
pub type LivechatAuditLogEventPublisher = Arc<dyn CrudEventPublisher<LivechatAuditLog> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopLivechatAuditLogEventPublisher = NoOpCrudEventPublisher<LivechatAuditLog>;
