//! Event handler trait for MemberHistory events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::MemberHistoryEvent;

/// Event handler for MemberHistory events.
/// Implement this trait to react to MemberHistory lifecycle events.
pub trait MemberHistoryEventHandler: EventHandler<MemberHistoryEvent> {}
