//! Domain events for OperatorProfile entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use crate::domain::entity::OperatorProfile;
use backbone_messaging::CrudEvent;

/// Domain events for OperatorProfile — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<OperatorProfile>)` variant.
pub type OperatorProfileEvent = CrudEvent<OperatorProfile>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for OperatorProfile events.
pub type OperatorProfileEventPublisher = Arc<dyn CrudEventPublisher<OperatorProfile> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopOperatorProfileEventPublisher = NoOpCrudEventPublisher<OperatorProfile>;
