//! Event handler trait for OperatorExpertise events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::OperatorExpertiseEvent;

/// Event handler for OperatorExpertise events.
/// Implement this trait to react to OperatorExpertise lifecycle events.
pub trait OperatorExpertiseEventHandler: EventHandler<OperatorExpertiseEvent> {}
