//! Event handler trait for OperatorProfile events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::OperatorProfileEvent;
use backbone_messaging::EventHandler;

/// Event handler for OperatorProfile events.
/// Implement this trait to react to OperatorProfile lifecycle events.
pub trait OperatorProfileEventHandler: EventHandler<OperatorProfileEvent> {}
