//! Event handler trait for Rating events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::RatingEvent;

/// Event handler for Rating events.
/// Implement this trait to react to Rating lifecycle events.
pub trait RatingEventHandler: EventHandler<RatingEvent> {}
