//! Event handler trait for SessionTag events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::SessionTagEvent;
use backbone_messaging::EventHandler;

/// Event handler for SessionTag events.
/// Implement this trait to react to SessionTag lifecycle events.
pub trait SessionTagEventHandler: EventHandler<SessionTagEvent> {}
