//! Event handler trait for Session events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::SessionEvent;
use backbone_messaging::EventHandler;

/// Event handler for Session events.
/// Implement this trait to react to Session lifecycle events.
pub trait SessionEventHandler: EventHandler<SessionEvent> {}
