//! ChatbotMessage seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial ChatbotMessage data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// CHATBOTMESSAGE SEEDER
// ============================================================================

/// Seeder for chatbot_message
pub struct SeedChatbotMessageSeeder;

impl SeedChatbotMessageSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedChatbotMessageSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedChatbotMessageSeeder {
    fn name(&self) -> &'static str {
        "SeedChatbotMessageSeeder"
    }

    fn order(&self) -> i32 {
        5
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if livechat.chatbot_messages table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM livechat.chatbot_messages")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/chatbot_message_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM livechat.chatbot_messages")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
