//! ConversationTag seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial ConversationTag data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// CONVERSATIONTAG SEEDER
// ============================================================================

/// Seeder for conversation_tag
pub struct SeedConversationTagSeeder;

impl SeedConversationTagSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedConversationTagSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedConversationTagSeeder {
    fn name(&self) -> &'static str {
        "SeedConversationTagSeeder"
    }

    fn order(&self) -> i32 {
        9
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if livechat.conversation_tags table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM livechat.conversation_tags")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/conversation_tag_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM livechat.conversation_tags")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
