//! Database seeders for the livechat module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides seed data for initial database setup.
//! Seeders can be run via the seeder binary or CLI.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

mod channel_member_seeder;
mod channel_rule_seeder;
mod channel_seeder;
mod chatbot_answer_seeder;
mod chatbot_message_seeder;
mod chatbot_script_seeder;
mod chatbot_step_seeder;
mod chatbot_step_trigger_seeder;
mod conversation_tag_seeder;
mod expertise_tag_seeder;
mod livechat_audit_log_seeder;
mod member_history_seeder;
mod operator_expertise_seeder;
mod operator_profile_seeder;
mod rating_seeder;
mod session_seeder;
mod session_tag_seeder;

pub use channel_member_seeder::SeedChannelMemberSeeder;
pub use channel_rule_seeder::SeedChannelRuleSeeder;
pub use channel_seeder::SeedChannelSeeder;
pub use chatbot_answer_seeder::SeedChatbotAnswerSeeder;
pub use chatbot_message_seeder::SeedChatbotMessageSeeder;
pub use chatbot_script_seeder::SeedChatbotScriptSeeder;
pub use chatbot_step_seeder::SeedChatbotStepSeeder;
pub use chatbot_step_trigger_seeder::SeedChatbotStepTriggerSeeder;
pub use conversation_tag_seeder::SeedConversationTagSeeder;
pub use expertise_tag_seeder::SeedExpertiseTagSeeder;
pub use livechat_audit_log_seeder::SeedLivechatAuditLogSeeder;
pub use member_history_seeder::SeedMemberHistorySeeder;
pub use operator_expertise_seeder::SeedOperatorExpertiseSeeder;
pub use operator_profile_seeder::SeedOperatorProfileSeeder;
pub use rating_seeder::SeedRatingSeeder;
pub use session_seeder::SeedSessionSeeder;
pub use session_tag_seeder::SeedSessionTagSeeder;

// ============================================================================
// SEEDER TRAIT
// ============================================================================

/// Trait for database seeders
#[async_trait]
pub trait Seeder {
    /// Get the name of this seeder
    fn name(&self) -> &'static str;

    /// Get the order in which this seeder should run
    fn order(&self) -> i32;

    /// Check if this seeder should run (e.g., check if data already exists)
    async fn should_run(&self, pool: &PgPool) -> Result<bool>;

    /// Run the seeder
    async fn run(&self, pool: &PgPool) -> Result<()>;

    /// Rollback the seeder (optional)
    async fn rollback(&self, _pool: &PgPool) -> Result<()> {
        Ok(())
    }
}

// ============================================================================
// SEEDER TYPE
// ============================================================================

/// Type of seeder
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SeederType {
    /// Reference data (required for application to function)
    Reference,
    /// Initial production data
    Production,
    /// Development/testing data
    Development,
    /// Test data (for automated tests)
    Test,
}

// ============================================================================
// CUSTOM SEEDERS
// ============================================================================

// <<< CUSTOM SEEDERS START >>>
// Add custom seeders here
// <<< CUSTOM SEEDERS END >>>
