//! Repository trait for Channel aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Channel aggregate.
//! Implementation is in the infrastructure layer.

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use crate::domain::entity::{Channel, LivechatMaxSessionsMode};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ChannelPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ChannelPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ChannelPaginatedResult {
    pub data: Vec<Channel>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ChannelFilter {
    pub name: Option<String>,
    pub website_id: Option<Uuid>,
    pub button_text: Option<String>,
    pub welcome_message: Option<String>,
    pub max_sessions_mode: Option<LivechatMaxSessionsMode>,
    pub block_assignment_during_call: Option<bool>,
    pub is_active: Option<bool>,
    pub company_id: Option<Uuid>,
}

impl ChannelFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.name.is_some()
            || self.website_id.is_some()
            || self.button_text.is_some()
            || self.welcome_message.is_some()
            || self.max_sessions_mode.is_some()
            || self.block_assignment_during_call.is_some()
            || self.is_active.is_some()
            || self.company_id.is_some()
    }
}

/// Repository trait for Channel aggregate
///
/// This trait defines the persistence contract for Channel entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ChannelRepository: Send + Sync {
    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new channel entity
    async fn save(&self, entity: &Channel) -> Result<Channel>;

    /// Find channel by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Channel>>;

    /// Find all channel entities
    async fn find_all(&self) -> Result<Vec<Channel>>;

    /// Update channel by ID
    async fn update(&self, id: &str, entity: &Channel) -> Result<Option<Channel>>;

    /// Delete channel by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List channel with pagination
    async fn list(&self, params: ChannelPaginationParams) -> Result<ChannelPaginatedResult>;

    /// List channel with pagination and filters
    async fn list_with_filters(
        &self,
        params: ChannelPaginationParams,
        filters: ChannelFilter,
    ) -> Result<ChannelPaginatedResult>;

    /// Count all channel entities
    async fn count(&self) -> Result<u64>;

    /// Count channel entities matching filters
    async fn count_with_filters(&self, filters: ChannelFilter) -> Result<u64>;

    /// Check if channel exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete channel by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted channel by ID
    async fn restore(&self, id: &str) -> Result<Option<Channel>>;

    /// List soft-deleted channel entities
    async fn list_deleted(&self, params: ChannelPaginationParams)
        -> Result<ChannelPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save channel entities
    async fn bulk_save(&self, entities: &[Channel]) -> Result<Vec<Channel>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
