//! Repository trait for ChannelRule aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the ChannelRule aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{ChannelRule, LivechatChatbotCondition, LivechatRuleAction};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ChannelRulePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ChannelRulePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ChannelRulePaginatedResult {
    pub data: Vec<ChannelRule>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ChannelRuleFilter {
    pub channel_id: Option<Uuid>,
    pub regex_url: Option<String>,
    pub action: Option<LivechatRuleAction>,
    pub chatbot_script_id: Option<Uuid>,
    pub chatbot_enabled_condition: Option<LivechatChatbotCondition>,
}

impl ChannelRuleFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.channel_id.is_some() || self.regex_url.is_some() || self.action.is_some() || self.chatbot_script_id.is_some() || self.chatbot_enabled_condition.is_some()
    }
}

/// Repository trait for ChannelRule aggregate
///
/// This trait defines the persistence contract for ChannelRule entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ChannelRuleRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new channel_rule entity
    async fn save(&self, entity: &ChannelRule) -> Result<ChannelRule>;

    /// Find channel_rule by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<ChannelRule>>;

    /// Find all channel_rule entities
    async fn find_all(&self) -> Result<Vec<ChannelRule>>;

    /// Update channel_rule by ID
    async fn update(&self, id: &str, entity: &ChannelRule) -> Result<Option<ChannelRule>>;

    /// Delete channel_rule by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List channel_rule with pagination
    async fn list(&self, params: ChannelRulePaginationParams) -> Result<ChannelRulePaginatedResult>;

    /// List channel_rule with pagination and filters
    async fn list_with_filters(&self, params: ChannelRulePaginationParams, filters: ChannelRuleFilter) -> Result<ChannelRulePaginatedResult>;

    /// Count all channel_rule entities
    async fn count(&self) -> Result<u64>;

    /// Count channel_rule entities matching filters
    async fn count_with_filters(&self, filters: ChannelRuleFilter) -> Result<u64>;

    /// Check if channel_rule exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete channel_rule by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted channel_rule by ID
    async fn restore(&self, id: &str) -> Result<Option<ChannelRule>>;

    /// List soft-deleted channel_rule entities
    async fn list_deleted(&self, params: ChannelRulePaginationParams) -> Result<ChannelRulePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save channel_rule entities
    async fn bulk_save(&self, entities: &[ChannelRule]) -> Result<Vec<ChannelRule>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
