//! Repository trait for ChatbotScript aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the ChatbotScript aggregate.
//! Implementation is in the infrastructure layer.

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use crate::domain::entity::ChatbotScript;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ChatbotScriptPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ChatbotScriptPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ChatbotScriptPaginatedResult {
    pub data: Vec<ChatbotScript>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ChatbotScriptFilter {
    pub title: Option<String>,
    pub is_active: Option<bool>,
    pub company_id: Option<Uuid>,
}

impl ChatbotScriptFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.title.is_some() || self.is_active.is_some() || self.company_id.is_some()
    }
}

/// Repository trait for ChatbotScript aggregate
///
/// This trait defines the persistence contract for ChatbotScript entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ChatbotScriptRepository: Send + Sync {
    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new chatbot_script entity
    async fn save(&self, entity: &ChatbotScript) -> Result<ChatbotScript>;

    /// Find chatbot_script by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<ChatbotScript>>;

    /// Find all chatbot_script entities
    async fn find_all(&self) -> Result<Vec<ChatbotScript>>;

    /// Update chatbot_script by ID
    async fn update(&self, id: &str, entity: &ChatbotScript) -> Result<Option<ChatbotScript>>;

    /// Delete chatbot_script by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List chatbot_script with pagination
    async fn list(
        &self,
        params: ChatbotScriptPaginationParams,
    ) -> Result<ChatbotScriptPaginatedResult>;

    /// List chatbot_script with pagination and filters
    async fn list_with_filters(
        &self,
        params: ChatbotScriptPaginationParams,
        filters: ChatbotScriptFilter,
    ) -> Result<ChatbotScriptPaginatedResult>;

    /// Count all chatbot_script entities
    async fn count(&self) -> Result<u64>;

    /// Count chatbot_script entities matching filters
    async fn count_with_filters(&self, filters: ChatbotScriptFilter) -> Result<u64>;

    /// Check if chatbot_script exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete chatbot_script by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted chatbot_script by ID
    async fn restore(&self, id: &str) -> Result<Option<ChatbotScript>>;

    /// List soft-deleted chatbot_script entities
    async fn list_deleted(
        &self,
        params: ChatbotScriptPaginationParams,
    ) -> Result<ChatbotScriptPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save chatbot_script entities
    async fn bulk_save(&self, entities: &[ChatbotScript]) -> Result<Vec<ChatbotScript>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
