//! Repository trait for ChatbotStepTrigger aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the ChatbotStepTrigger aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::ChatbotStepTrigger;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ChatbotStepTriggerPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ChatbotStepTriggerPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ChatbotStepTriggerPaginatedResult {
    pub data: Vec<ChatbotStepTrigger>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ChatbotStepTriggerFilter {
    pub answer_id: Option<Uuid>,
    pub target_step_id: Option<Uuid>,
}

impl ChatbotStepTriggerFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.answer_id.is_some() || self.target_step_id.is_some()
    }
}

/// Repository trait for ChatbotStepTrigger aggregate
///
/// This trait defines the persistence contract for ChatbotStepTrigger entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ChatbotStepTriggerRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new chatbot_step_trigger entity
    async fn save(&self, entity: &ChatbotStepTrigger) -> Result<ChatbotStepTrigger>;

    /// Find chatbot_step_trigger by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<ChatbotStepTrigger>>;

    /// Find all chatbot_step_trigger entities
    async fn find_all(&self) -> Result<Vec<ChatbotStepTrigger>>;

    /// Update chatbot_step_trigger by ID
    async fn update(&self, id: &str, entity: &ChatbotStepTrigger) -> Result<Option<ChatbotStepTrigger>>;

    /// Delete chatbot_step_trigger by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List chatbot_step_trigger with pagination
    async fn list(&self, params: ChatbotStepTriggerPaginationParams) -> Result<ChatbotStepTriggerPaginatedResult>;

    /// List chatbot_step_trigger with pagination and filters
    async fn list_with_filters(&self, params: ChatbotStepTriggerPaginationParams, filters: ChatbotStepTriggerFilter) -> Result<ChatbotStepTriggerPaginatedResult>;

    /// Count all chatbot_step_trigger entities
    async fn count(&self) -> Result<u64>;

    /// Count chatbot_step_trigger entities matching filters
    async fn count_with_filters(&self, filters: ChatbotStepTriggerFilter) -> Result<u64>;

    /// Check if chatbot_step_trigger exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete chatbot_step_trigger by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted chatbot_step_trigger by ID
    async fn restore(&self, id: &str) -> Result<Option<ChatbotStepTrigger>>;

    /// List soft-deleted chatbot_step_trigger entities
    async fn list_deleted(&self, params: ChatbotStepTriggerPaginationParams) -> Result<ChatbotStepTriggerPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save chatbot_step_trigger entities
    async fn bulk_save(&self, entities: &[ChatbotStepTrigger]) -> Result<Vec<ChatbotStepTrigger>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
