//! Repository trait for ChatbotStep aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the ChatbotStep aggregate.
//! Implementation is in the infrastructure layer.

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use crate::domain::entity::{ChatbotStep, LivechatStepType};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ChatbotStepPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ChatbotStepPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ChatbotStepPaginatedResult {
    pub data: Vec<ChatbotStep>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ChatbotStepFilter {
    pub chatbot_script_id: Option<Uuid>,
    pub step_type: Option<LivechatStepType>,
    pub message: Option<String>,
    pub company_id: Option<Uuid>,
}

impl ChatbotStepFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.chatbot_script_id.is_some()
            || self.step_type.is_some()
            || self.message.is_some()
            || self.company_id.is_some()
    }
}

/// Repository trait for ChatbotStep aggregate
///
/// This trait defines the persistence contract for ChatbotStep entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ChatbotStepRepository: Send + Sync {
    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new chatbot_step entity
    async fn save(&self, entity: &ChatbotStep) -> Result<ChatbotStep>;

    /// Find chatbot_step by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<ChatbotStep>>;

    /// Find all chatbot_step entities
    async fn find_all(&self) -> Result<Vec<ChatbotStep>>;

    /// Update chatbot_step by ID
    async fn update(&self, id: &str, entity: &ChatbotStep) -> Result<Option<ChatbotStep>>;

    /// Delete chatbot_step by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List chatbot_step with pagination
    async fn list(&self, params: ChatbotStepPaginationParams)
        -> Result<ChatbotStepPaginatedResult>;

    /// List chatbot_step with pagination and filters
    async fn list_with_filters(
        &self,
        params: ChatbotStepPaginationParams,
        filters: ChatbotStepFilter,
    ) -> Result<ChatbotStepPaginatedResult>;

    /// Count all chatbot_step entities
    async fn count(&self) -> Result<u64>;

    /// Count chatbot_step entities matching filters
    async fn count_with_filters(&self, filters: ChatbotStepFilter) -> Result<u64>;

    /// Check if chatbot_step exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete chatbot_step by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted chatbot_step by ID
    async fn restore(&self, id: &str) -> Result<Option<ChatbotStep>>;

    /// List soft-deleted chatbot_step entities
    async fn list_deleted(
        &self,
        params: ChatbotStepPaginationParams,
    ) -> Result<ChatbotStepPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save chatbot_step entities
    async fn bulk_save(&self, entities: &[ChatbotStep]) -> Result<Vec<ChatbotStep>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
