//! Repository trait for ChatbotMessage aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the ChatbotMessage aggregate.
//! Implementation is in the infrastructure layer.

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use crate::domain::entity::ChatbotMessage;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ChatbotMessagePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ChatbotMessagePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ChatbotMessagePaginatedResult {
    pub data: Vec<ChatbotMessage>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ChatbotMessageFilter {
    pub session_id: Option<Uuid>,
    pub step_id: Option<Uuid>,
    pub carrier_message_id: Option<String>,
    pub selected_answer_id: Option<Uuid>,
    pub visitor_answer: Option<String>,
    pub company_id: Option<Uuid>,
}

impl ChatbotMessageFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.session_id.is_some()
            || self.step_id.is_some()
            || self.carrier_message_id.is_some()
            || self.selected_answer_id.is_some()
            || self.visitor_answer.is_some()
            || self.company_id.is_some()
    }
}

/// Repository trait for ChatbotMessage aggregate
///
/// This trait defines the persistence contract for ChatbotMessage entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ChatbotMessageRepository: Send + Sync {
    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new chatbot_message entity
    async fn save(&self, entity: &ChatbotMessage) -> Result<ChatbotMessage>;

    /// Find chatbot_message by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<ChatbotMessage>>;

    /// Find all chatbot_message entities
    async fn find_all(&self) -> Result<Vec<ChatbotMessage>>;

    /// Update chatbot_message by ID
    async fn update(&self, id: &str, entity: &ChatbotMessage) -> Result<Option<ChatbotMessage>>;

    /// Delete chatbot_message by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List chatbot_message with pagination
    async fn list(
        &self,
        params: ChatbotMessagePaginationParams,
    ) -> Result<ChatbotMessagePaginatedResult>;

    /// List chatbot_message with pagination and filters
    async fn list_with_filters(
        &self,
        params: ChatbotMessagePaginationParams,
        filters: ChatbotMessageFilter,
    ) -> Result<ChatbotMessagePaginatedResult>;

    /// Count all chatbot_message entities
    async fn count(&self) -> Result<u64>;

    /// Count chatbot_message entities matching filters
    async fn count_with_filters(&self, filters: ChatbotMessageFilter) -> Result<u64>;

    /// Check if chatbot_message exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete chatbot_message by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted chatbot_message by ID
    async fn restore(&self, id: &str) -> Result<Option<ChatbotMessage>>;

    /// List soft-deleted chatbot_message entities
    async fn list_deleted(
        &self,
        params: ChatbotMessagePaginationParams,
    ) -> Result<ChatbotMessagePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save chatbot_message entities
    async fn bulk_save(&self, entities: &[ChatbotMessage]) -> Result<Vec<ChatbotMessage>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
