//! Repository trait for ChatbotAnswer aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the ChatbotAnswer aggregate.
//! Implementation is in the infrastructure layer.

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use crate::domain::entity::ChatbotAnswer;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ChatbotAnswerPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ChatbotAnswerPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ChatbotAnswerPaginatedResult {
    pub data: Vec<ChatbotAnswer>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ChatbotAnswerFilter {
    pub question_step_id: Option<Uuid>,
    pub label: Option<String>,
    pub company_id: Option<Uuid>,
}

impl ChatbotAnswerFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.question_step_id.is_some() || self.label.is_some() || self.company_id.is_some()
    }
}

/// Repository trait for ChatbotAnswer aggregate
///
/// This trait defines the persistence contract for ChatbotAnswer entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ChatbotAnswerRepository: Send + Sync {
    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new chatbot_answer entity
    async fn save(&self, entity: &ChatbotAnswer) -> Result<ChatbotAnswer>;

    /// Find chatbot_answer by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<ChatbotAnswer>>;

    /// Find all chatbot_answer entities
    async fn find_all(&self) -> Result<Vec<ChatbotAnswer>>;

    /// Update chatbot_answer by ID
    async fn update(&self, id: &str, entity: &ChatbotAnswer) -> Result<Option<ChatbotAnswer>>;

    /// Delete chatbot_answer by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List chatbot_answer with pagination
    async fn list(
        &self,
        params: ChatbotAnswerPaginationParams,
    ) -> Result<ChatbotAnswerPaginatedResult>;

    /// List chatbot_answer with pagination and filters
    async fn list_with_filters(
        &self,
        params: ChatbotAnswerPaginationParams,
        filters: ChatbotAnswerFilter,
    ) -> Result<ChatbotAnswerPaginatedResult>;

    /// Count all chatbot_answer entities
    async fn count(&self) -> Result<u64>;

    /// Count chatbot_answer entities matching filters
    async fn count_with_filters(&self, filters: ChatbotAnswerFilter) -> Result<u64>;

    /// Check if chatbot_answer exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete chatbot_answer by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted chatbot_answer by ID
    async fn restore(&self, id: &str) -> Result<Option<ChatbotAnswer>>;

    /// List soft-deleted chatbot_answer entities
    async fn list_deleted(
        &self,
        params: ChatbotAnswerPaginationParams,
    ) -> Result<ChatbotAnswerPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save chatbot_answer entities
    async fn bulk_save(&self, entities: &[ChatbotAnswer]) -> Result<Vec<ChatbotAnswer>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
