//! Repository trait for ConversationTag aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the ConversationTag aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;

use crate::domain::entity::ConversationTag;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ConversationTagPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ConversationTagPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ConversationTagPaginatedResult {
    pub data: Vec<ConversationTag>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ConversationTagFilter {
    pub name: Option<String>,
}

impl ConversationTagFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.name.is_some()
    }
}

/// Repository trait for ConversationTag aggregate
///
/// This trait defines the persistence contract for ConversationTag entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ConversationTagRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new conversation_tag entity
    async fn save(&self, entity: &ConversationTag) -> Result<ConversationTag>;

    /// Find conversation_tag by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<ConversationTag>>;

    /// Find all conversation_tag entities
    async fn find_all(&self) -> Result<Vec<ConversationTag>>;

    /// Update conversation_tag by ID
    async fn update(&self, id: &str, entity: &ConversationTag) -> Result<Option<ConversationTag>>;

    /// Delete conversation_tag by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List conversation_tag with pagination
    async fn list(&self, params: ConversationTagPaginationParams) -> Result<ConversationTagPaginatedResult>;

    /// List conversation_tag with pagination and filters
    async fn list_with_filters(&self, params: ConversationTagPaginationParams, filters: ConversationTagFilter) -> Result<ConversationTagPaginatedResult>;

    /// Count all conversation_tag entities
    async fn count(&self) -> Result<u64>;

    /// Count conversation_tag entities matching filters
    async fn count_with_filters(&self, filters: ConversationTagFilter) -> Result<u64>;

    /// Check if conversation_tag exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete conversation_tag by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted conversation_tag by ID
    async fn restore(&self, id: &str) -> Result<Option<ConversationTag>>;

    /// List soft-deleted conversation_tag entities
    async fn list_deleted(&self, params: ConversationTagPaginationParams) -> Result<ConversationTagPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save conversation_tag entities
    async fn bulk_save(&self, entities: &[ConversationTag]) -> Result<Vec<ConversationTag>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
