//! Repository trait for MemberHistory aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the MemberHistory aggregate.
//! Implementation is in the infrastructure layer.

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use crate::domain::entity::{LivechatPersona, MemberHistory};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct MemberHistoryPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl MemberHistoryPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct MemberHistoryPaginatedResult {
    pub data: Vec<MemberHistory>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct MemberHistoryFilter {
    pub session_id: Option<Uuid>,
    pub persona: Option<LivechatPersona>,
    pub operator_user_id: Option<Uuid>,
    pub visitor_key: Option<String>,
    pub chatbot_script_id: Option<Uuid>,
    pub company_id: Option<Uuid>,
}

impl MemberHistoryFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.session_id.is_some()
            || self.persona.is_some()
            || self.operator_user_id.is_some()
            || self.visitor_key.is_some()
            || self.chatbot_script_id.is_some()
            || self.company_id.is_some()
    }
}

/// Repository trait for MemberHistory aggregate
///
/// This trait defines the persistence contract for MemberHistory entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait MemberHistoryRepository: Send + Sync {
    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new member_history entity
    async fn save(&self, entity: &MemberHistory) -> Result<MemberHistory>;

    /// Find member_history by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<MemberHistory>>;

    /// Find all member_history entities
    async fn find_all(&self) -> Result<Vec<MemberHistory>>;

    /// Update member_history by ID
    async fn update(&self, id: &str, entity: &MemberHistory) -> Result<Option<MemberHistory>>;

    /// Delete member_history by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List member_history with pagination
    async fn list(
        &self,
        params: MemberHistoryPaginationParams,
    ) -> Result<MemberHistoryPaginatedResult>;

    /// List member_history with pagination and filters
    async fn list_with_filters(
        &self,
        params: MemberHistoryPaginationParams,
        filters: MemberHistoryFilter,
    ) -> Result<MemberHistoryPaginatedResult>;

    /// Count all member_history entities
    async fn count(&self) -> Result<u64>;

    /// Count member_history entities matching filters
    async fn count_with_filters(&self, filters: MemberHistoryFilter) -> Result<u64>;

    /// Check if member_history exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete member_history by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted member_history by ID
    async fn restore(&self, id: &str) -> Result<Option<MemberHistory>>;

    /// List soft-deleted member_history entities
    async fn list_deleted(
        &self,
        params: MemberHistoryPaginationParams,
    ) -> Result<MemberHistoryPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save member_history entities
    async fn bulk_save(&self, entities: &[MemberHistory]) -> Result<Vec<MemberHistory>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
