//! Repository trait for OperatorProfile aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the OperatorProfile aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::OperatorProfile;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct OperatorProfilePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl OperatorProfilePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct OperatorProfilePaginatedResult {
    pub data: Vec<OperatorProfile>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct OperatorProfileFilter {
    pub user_id: Option<Uuid>,
    pub display_name: Option<String>,
}

impl OperatorProfileFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.user_id.is_some() || self.display_name.is_some()
    }
}

/// Repository trait for OperatorProfile aggregate
///
/// This trait defines the persistence contract for OperatorProfile entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait OperatorProfileRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new operator_profile entity
    async fn save(&self, entity: &OperatorProfile) -> Result<OperatorProfile>;

    /// Find operator_profile by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<OperatorProfile>>;

    /// Find all operator_profile entities
    async fn find_all(&self) -> Result<Vec<OperatorProfile>>;

    /// Update operator_profile by ID
    async fn update(&self, id: &str, entity: &OperatorProfile) -> Result<Option<OperatorProfile>>;

    /// Delete operator_profile by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List operator_profile with pagination
    async fn list(&self, params: OperatorProfilePaginationParams) -> Result<OperatorProfilePaginatedResult>;

    /// List operator_profile with pagination and filters
    async fn list_with_filters(&self, params: OperatorProfilePaginationParams, filters: OperatorProfileFilter) -> Result<OperatorProfilePaginatedResult>;

    /// Count all operator_profile entities
    async fn count(&self) -> Result<u64>;

    /// Count operator_profile entities matching filters
    async fn count_with_filters(&self, filters: OperatorProfileFilter) -> Result<u64>;

    /// Check if operator_profile exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete operator_profile by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted operator_profile by ID
    async fn restore(&self, id: &str) -> Result<Option<OperatorProfile>>;

    /// List soft-deleted operator_profile entities
    async fn list_deleted(&self, params: OperatorProfilePaginationParams) -> Result<OperatorProfilePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save operator_profile entities
    async fn bulk_save(&self, entities: &[OperatorProfile]) -> Result<Vec<OperatorProfile>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
