//! Repository trait for SessionTag aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the SessionTag aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::SessionTag;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SessionTagPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl SessionTagPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct SessionTagPaginatedResult {
    pub data: Vec<SessionTag>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SessionTagFilter {
    pub session_id: Option<Uuid>,
    pub tag_id: Option<Uuid>,
}

impl SessionTagFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.session_id.is_some() || self.tag_id.is_some()
    }
}

/// Repository trait for SessionTag aggregate
///
/// This trait defines the persistence contract for SessionTag entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait SessionTagRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new session_tag entity
    async fn save(&self, entity: &SessionTag) -> Result<SessionTag>;

    /// Find session_tag by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<SessionTag>>;

    /// Find all session_tag entities
    async fn find_all(&self) -> Result<Vec<SessionTag>>;

    /// Update session_tag by ID
    async fn update(&self, id: &str, entity: &SessionTag) -> Result<Option<SessionTag>>;

    /// Delete session_tag by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List session_tag with pagination
    async fn list(&self, params: SessionTagPaginationParams) -> Result<SessionTagPaginatedResult>;

    /// List session_tag with pagination and filters
    async fn list_with_filters(&self, params: SessionTagPaginationParams, filters: SessionTagFilter) -> Result<SessionTagPaginatedResult>;

    /// Count all session_tag entities
    async fn count(&self) -> Result<u64>;

    /// Count session_tag entities matching filters
    async fn count_with_filters(&self, filters: SessionTagFilter) -> Result<u64>;

    /// Check if session_tag exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete session_tag by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted session_tag by ID
    async fn restore(&self, id: &str) -> Result<Option<SessionTag>>;

    /// List soft-deleted session_tag entities
    async fn list_deleted(&self, params: SessionTagPaginationParams) -> Result<SessionTagPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save session_tag entities
    async fn bulk_save(&self, entities: &[SessionTag]) -> Result<Vec<SessionTag>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
