//! Repository trait for Session aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Session aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Session, LivechatCloseReason, LivechatFailure, LivechatSessionOutcome, LivechatSessionStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SessionPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl SessionPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct SessionPaginatedResult {
    pub data: Vec<Session>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SessionFilter {
    pub channel_id: Option<Uuid>,
    pub title: Option<String>,
    pub status: Option<LivechatSessionStatus>,
    pub failure: Option<LivechatFailure>,
    pub outcome: Option<LivechatSessionOutcome>,
    pub close_reason: Option<LivechatCloseReason>,
    pub operator_user_id: Option<Uuid>,
    pub chatbot_current_step_id: Option<Uuid>,
    pub website_visitor_id: Option<Uuid>,
    pub visitor_country_code: Option<String>,
    pub visitor_timezone: Option<String>,
    pub is_pending_request: Option<bool>,
    pub crm_lead_id: Option<Uuid>,
    pub visitor_language: Option<String>,
    pub is_test: Option<bool>,
    pub error_detail: Option<String>,
}

impl SessionFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.channel_id.is_some() || self.title.is_some() || self.status.is_some() || self.failure.is_some() || self.outcome.is_some() || self.close_reason.is_some() || self.operator_user_id.is_some() || self.chatbot_current_step_id.is_some() || self.website_visitor_id.is_some() || self.visitor_country_code.is_some() || self.visitor_timezone.is_some() || self.is_pending_request.is_some() || self.crm_lead_id.is_some() || self.visitor_language.is_some() || self.is_test.is_some() || self.error_detail.is_some()
    }
}

/// Repository trait for Session aggregate
///
/// This trait defines the persistence contract for Session entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait SessionRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new session entity
    async fn save(&self, entity: &Session) -> Result<Session>;

    /// Find session by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Session>>;

    /// Find all session entities
    async fn find_all(&self) -> Result<Vec<Session>>;

    /// Update session by ID
    async fn update(&self, id: &str, entity: &Session) -> Result<Option<Session>>;

    /// Delete session by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List session with pagination
    async fn list(&self, params: SessionPaginationParams) -> Result<SessionPaginatedResult>;

    /// List session with pagination and filters
    async fn list_with_filters(&self, params: SessionPaginationParams, filters: SessionFilter) -> Result<SessionPaginatedResult>;

    /// Count all session entities
    async fn count(&self) -> Result<u64>;

    /// Count session entities matching filters
    async fn count_with_filters(&self, filters: SessionFilter) -> Result<u64>;

    /// Check if session exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete session by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted session by ID
    async fn restore(&self, id: &str) -> Result<Option<Session>>;

    /// List soft-deleted session entities
    async fn list_deleted(&self, params: SessionPaginationParams) -> Result<SessionPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save session entities
    async fn bulk_save(&self, entities: &[Session]) -> Result<Vec<Session>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
