//! Repository for ChannelMember entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<ChannelMember, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::ChannelMember;

/// Table name for ChannelMember entities
pub const TABLE_NAME: &str = "livechat.channel_members";

/// Repository for ChannelMember entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ChannelMemberRepository(
    backbone_orm::GenericCrudRepository<ChannelMember, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ChannelMemberRepository {
    type Target = backbone_orm::GenericCrudRepository<ChannelMember, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl ChannelMemberRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(ChannelMemberRepository, ChannelMember, soft_delete);
