//! Repository for ChannelRule entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<ChannelRule, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::ChannelRule;

/// Table name for ChannelRule entities
pub const TABLE_NAME: &str = "livechat.channel_rules";

/// Repository for ChannelRule entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ChannelRuleRepository(
    backbone_orm::GenericCrudRepository<ChannelRule, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ChannelRuleRepository {
    type Target = backbone_orm::GenericCrudRepository<ChannelRule, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl ChannelRuleRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(ChannelRuleRepository, ChannelRule, soft_delete);
