//! Repository for ChatbotMessage entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<ChatbotMessage, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::ChatbotMessage;

/// Table name for ChatbotMessage entities
pub const TABLE_NAME: &str = "livechat.chatbot_messages";

/// Repository for ChatbotMessage entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ChatbotMessageRepository(
    backbone_orm::GenericCrudRepository<ChatbotMessage, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ChatbotMessageRepository {
    type Target = backbone_orm::GenericCrudRepository<ChatbotMessage, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl ChatbotMessageRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(ChatbotMessageRepository, ChatbotMessage, soft_delete);
