//! Repository for ChatbotStep entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<ChatbotStep, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::ChatbotStep;

/// Table name for ChatbotStep entities
pub const TABLE_NAME: &str = "livechat.chatbot_steps";

/// Repository for ChatbotStep entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ChatbotStepRepository(
    backbone_orm::GenericCrudRepository<ChatbotStep, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ChatbotStepRepository {
    type Target = backbone_orm::GenericCrudRepository<ChatbotStep, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl ChatbotStepRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(ChatbotStepRepository, ChatbotStep, soft_delete);
