//! Repository for ChatbotScript entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<ChatbotScript, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::ChatbotScript;

/// Table name for ChatbotScript entities
pub const TABLE_NAME: &str = "livechat.chatbot_scripts";

/// Repository for ChatbotScript entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ChatbotScriptRepository(
    backbone_orm::GenericCrudRepository<ChatbotScript, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ChatbotScriptRepository {
    type Target = backbone_orm::GenericCrudRepository<ChatbotScript, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl ChatbotScriptRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(ChatbotScriptRepository, ChatbotScript, soft_delete);
