//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod channel_repository;
mod channel_member_repository;
mod channel_rule_repository;
mod chatbot_answer_repository;
mod chatbot_message_repository;
mod chatbot_script_repository;
mod chatbot_step_repository;
mod chatbot_step_trigger_repository;
mod conversation_tag_repository;
mod expertise_tag_repository;
mod livechat_audit_log_repository;
mod member_history_repository;
mod operator_expertise_repository;
mod operator_profile_repository;
mod rating_repository;
mod session_repository;
mod session_tag_repository;

// Custom persistence modules
// <<< CUSTOM
// Hand-written repositories carrying the verbs' transactional SQL
// (user-owned; see metaphor.codegen.yaml). The generated CRUD
// repositories keep their own files — these are the verb layer's.
pub mod admin_config_repository;
pub mod chatbot_command_repository;
pub mod crm_bridge_repository;
pub mod report_repository;
pub mod selection_repository;
pub mod session_command_repository;
pub mod sweep_repository;
pub mod website_request_repository;

// Re-bind the caller's ambient org scope onto a transaction opened on the plain pool — the
// scope is task-local and a fresh pool transaction carries none of it. With no ambient scope
// (standalone deployment, jobs) the transaction stays plain: the module is tenant-agnostic and
// the composing service's tenancy decorator owns isolation (ADR-0029). Same convention as the
// backbone-pos write service's helper.
pub(crate) async fn relay_ambient_scope(conn: &mut sqlx::PgConnection) -> Result<(), sqlx::Error> {
    if let Some(scope) = backbone_orm::org_scope::current_org_scope() {
        backbone_orm::org_scope::bind_org_scope_on(conn, &scope).await?;
    }
    Ok(())
}
// END CUSTOM

// Re-exports
pub use channel_repository::ChannelRepository;
pub use channel_member_repository::ChannelMemberRepository;
pub use channel_rule_repository::ChannelRuleRepository;
pub use chatbot_answer_repository::ChatbotAnswerRepository;
pub use chatbot_message_repository::ChatbotMessageRepository;
pub use chatbot_script_repository::ChatbotScriptRepository;
pub use chatbot_step_repository::ChatbotStepRepository;
pub use chatbot_step_trigger_repository::ChatbotStepTriggerRepository;
pub use conversation_tag_repository::ConversationTagRepository;
pub use expertise_tag_repository::ExpertiseTagRepository;
pub use livechat_audit_log_repository::LivechatAuditLogRepository;
pub use member_history_repository::MemberHistoryRepository;
pub use operator_expertise_repository::OperatorExpertiseRepository;
pub use operator_profile_repository::OperatorProfileRepository;
pub use rating_repository::RatingRepository;
pub use session_repository::SessionRepository;
pub use session_tag_repository::SessionTagRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
pub use admin_config_repository::{
    AdminConfigRepository, AnswerInput, ChannelPatch, RuleInput, StepInput, STEP_TYPES,
};
pub use chatbot_command_repository::{
    AnswerRow, ChatbotCommandRepository, ChatbotMessageRow, StepRow,
};
pub use crm_bridge_repository::{CrmBridgeRepository, HarvestedContact};
pub use member_history_repository::{MemberHistoryLedgerRepository, MemberHistoryRow};
pub use rating_repository::{RatingCommandRepository, RatingRow};
pub use report_repository::{OutcomeMixRow, ReportRepository, SeriesBucketRow, SessionSummaryRow};
pub use selection_repository::{
    ongoing_window_expr, record_audit, AssignInput, AssignOutcome, ForwardAssignInput, LadderPick,
    SelectionRepository, ASSIGNMENT_BUFFER_SECS, ONGOING_WINDOW_SECS, PRESENCE_WINDOW_SECS,
};
pub use session_command_repository::{
    apply_message_tx, upsert_agent_ledger_tx, ChatbotMessageAppend, CloseOutcome, MessageDeltas,
    OpenSessionInput, PostMessageCommand, SessionCommandRepository, SessionListFilter, SessionRow,
};
pub use sweep_repository::{SweepOutcome, SweepRepository, SWEEP_BATCH};
pub use website_request_repository::{ChannelSummary, RuleMatch, WebsiteRequestRepository};
// END CUSTOM
