//! Repository for OperatorProfile entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<OperatorProfile, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::OperatorProfile;

/// Table name for OperatorProfile entities
pub const TABLE_NAME: &str = "livechat.operator_profiles";

/// Repository for OperatorProfile entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct OperatorProfileRepository(
    backbone_orm::GenericCrudRepository<OperatorProfile, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for OperatorProfileRepository {
    type Target = backbone_orm::GenericCrudRepository<OperatorProfile, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl OperatorProfileRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(OperatorProfileRepository, OperatorProfile, soft_delete);
