//! Validator for ChatbotAnswer entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<ChatbotAnswer>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank, RequiredString};
use crate::domain::entity::ChatbotAnswer;

/// Validator type alias for ChatbotAnswer entities.
pub type ChatbotAnswerValidator = EntityValidator<ChatbotAnswer>;

/// Build a validator for ChatbotAnswer with all schema-defined field rules.
pub fn chatbot_answer_validator() -> ChatbotAnswerValidator {
    EntityValidator::new()
        .rule(NonNegative::new("sequence", |e: &ChatbotAnswer| e.sequence as i64))
        .rule(RequiredString::new("label", |e: &ChatbotAnswer| &e.label))
        .rule(OptionalNotBlank::new("redirect_url", |e: &ChatbotAnswer| e.redirect_url.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
