//! Validator for ChatbotStep entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<ChatbotStep>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank};
use crate::domain::entity::ChatbotStep;

/// Validator type alias for ChatbotStep entities.
pub type ChatbotStepValidator = EntityValidator<ChatbotStep>;

/// Build a validator for ChatbotStep with all schema-defined field rules.
pub fn chatbot_step_validator() -> ChatbotStepValidator {
    EntityValidator::new()
        .rule(NonNegative::new("sequence", |e: &ChatbotStep| e.sequence as i64))
        .rule(OptionalNotBlank::new("message", |e: &ChatbotStep| e.message.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
