//! Validator for OperatorExpertise entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<OperatorExpertise>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use crate::domain::entity::OperatorExpertise;

/// Validator type alias for OperatorExpertise entities.
pub type OperatorExpertiseValidator = EntityValidator<OperatorExpertise>;

/// Build a validator for OperatorExpertise with all schema-defined field rules.
pub fn operator_expertise_validator() -> OperatorExpertiseValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
