//! Validator for Rating entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Rating>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank};
use crate::domain::entity::Rating;

/// Validator type alias for Rating entities.
pub type RatingValidator = EntityValidator<Rating>;

/// Build a validator for Rating with all schema-defined field rules.
pub fn rating_validator() -> RatingValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("comment", |e: &Rating| e.comment.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
