//! Validator for SessionTag entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<SessionTag>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use crate::domain::entity::SessionTag;

/// Validator type alias for SessionTag entities.
pub type SessionTagValidator = EntityValidator<SessionTag>;

/// Build a validator for SessionTag with all schema-defined field rules.
pub fn session_tag_validator() -> SessionTagValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
