//! Domain Entities
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod channel;
pub mod channel_member;
pub mod channel_rule;
pub mod chatbot_answer;
pub mod chatbot_message;
pub mod chatbot_script;
pub mod chatbot_step;
pub mod chatbot_step_trigger;
pub mod conversation_tag;
pub mod expertise_tag;
pub mod livechat_audit_log;
pub mod member_history;
pub mod operator_expertise;
pub mod operator_profile;
pub mod rating;
pub mod session;
pub mod session_tag;
pub mod livechat_max_sessions_mode;
pub mod livechat_rule_action;
pub mod livechat_chatbot_condition;
pub mod livechat_step_type;
pub mod livechat_audit_event;
pub mod livechat_persona;
pub mod livechat_rated_persona;
pub mod livechat_session_status;
pub mod livechat_failure;
pub mod livechat_session_outcome;
pub mod livechat_close_reason;

// Re-exports
pub use channel::Channel;
pub use channel::ChannelBuilder;
pub use channel::ChannelId;
pub use channel_member::ChannelMember;
pub use channel_member::ChannelMemberBuilder;
pub use channel_member::ChannelMemberId;
pub use channel_rule::ChannelRule;
pub use channel_rule::ChannelRuleBuilder;
pub use channel_rule::ChannelRuleId;
pub use chatbot_answer::ChatbotAnswer;
pub use chatbot_answer::ChatbotAnswerBuilder;
pub use chatbot_answer::ChatbotAnswerId;
pub use chatbot_message::ChatbotMessage;
pub use chatbot_message::ChatbotMessageBuilder;
pub use chatbot_message::ChatbotMessageId;
pub use chatbot_script::ChatbotScript;
pub use chatbot_script::ChatbotScriptBuilder;
pub use chatbot_script::ChatbotScriptId;
pub use chatbot_step::ChatbotStep;
pub use chatbot_step::ChatbotStepBuilder;
pub use chatbot_step::ChatbotStepId;
pub use chatbot_step_trigger::ChatbotStepTrigger;
pub use chatbot_step_trigger::ChatbotStepTriggerBuilder;
pub use chatbot_step_trigger::ChatbotStepTriggerId;
pub use conversation_tag::ConversationTag;
pub use conversation_tag::ConversationTagBuilder;
pub use conversation_tag::ConversationTagId;
pub use expertise_tag::ExpertiseTag;
pub use expertise_tag::ExpertiseTagBuilder;
pub use expertise_tag::ExpertiseTagId;
pub use livechat_audit_log::LivechatAuditLog;
pub use livechat_audit_log::LivechatAuditLogBuilder;
pub use livechat_audit_log::LivechatAuditLogId;
pub use member_history::MemberHistory;
pub use member_history::MemberHistoryBuilder;
pub use member_history::MemberHistoryId;
pub use operator_expertise::OperatorExpertise;
pub use operator_expertise::OperatorExpertiseBuilder;
pub use operator_expertise::OperatorExpertiseId;
pub use operator_profile::OperatorProfile;
pub use operator_profile::OperatorProfileBuilder;
pub use operator_profile::OperatorProfileId;
pub use rating::Rating;
pub use rating::RatingBuilder;
pub use rating::RatingId;
pub use session::Session;
pub use session::SessionBuilder;
pub use session::SessionId;
pub use session_tag::SessionTag;
pub use session_tag::SessionTagBuilder;
pub use session_tag::SessionTagId;
pub use livechat_max_sessions_mode::LivechatMaxSessionsMode;
pub use livechat_rule_action::LivechatRuleAction;
pub use livechat_chatbot_condition::LivechatChatbotCondition;
pub use livechat_step_type::LivechatStepType;
pub use livechat_audit_event::LivechatAuditEvent;
pub use livechat_persona::LivechatPersona;
pub use livechat_rated_persona::LivechatRatedPersona;
pub use livechat_session_status::LivechatSessionStatus;
pub use livechat_failure::LivechatFailure;
pub use livechat_session_outcome::LivechatSessionOutcome;
pub use livechat_close_reason::LivechatCloseReason;

// ==========================================================================
// Entity Trait
// ==========================================================================

use std::fmt::Debug;

/// Trait for domain entities
///
/// All generated entities implement this trait, providing
/// a common interface for working with domain objects.
pub trait Entity: Debug + Clone {
    /// The type of the entity's unique identifier
    type Id: Debug + Clone + PartialEq;

    /// Get the entity's unique identifier
    fn entity_id(&self) -> &Self::Id;

    /// Get the entity type name
    fn entity_type() -> &'static str;
}

// ==========================================================================
// Audit Metadata
// ==========================================================================

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

/// Audit metadata stored as JSONB in the database
///
/// This struct consolidates audit fields (timestamps and actors) into a single
/// JSONB column for efficient storage and flexible querying.
#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
pub struct AuditMetadata {
    /// Timestamp when the record was created
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_at: Option<DateTime<Utc>>,

    /// Timestamp when the record was last updated
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<DateTime<Utc>>,

    /// Timestamp when the record was soft-deleted
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deleted_at: Option<DateTime<Utc>>,

    /// User ID who created the record
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_by: Option<Uuid>,

    /// User ID who last updated the record
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_by: Option<Uuid>,

    /// User ID who deleted the record
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deleted_by: Option<Uuid>,
}

impl AuditMetadata {
    /// Create new audit metadata with created_at set to now
    pub fn new() -> Self {
        Self {
            created_at: Some(Utc::now()),
            ..Default::default()
        }
    }

    /// Create with creator ID
    pub fn with_creator(creator_id: Uuid) -> Self {
        Self {
            created_at: Some(Utc::now()),
            created_by: Some(creator_id),
            ..Default::default()
        }
    }

    /// Touch the record (update updated_at)
    pub fn touch(&mut self) {
        self.updated_at = Some(Utc::now());
    }

    /// Touch with updater ID
    pub fn touch_by(&mut self, updater_id: Uuid) {
        self.updated_at = Some(Utc::now());
        self.updated_by = Some(updater_id);
    }

    /// Soft delete the record
    pub fn soft_delete(&mut self) {
        self.deleted_at = Some(Utc::now());
    }

    /// Soft delete with deleter ID
    pub fn soft_delete_by(&mut self, deleter_id: Uuid) {
        self.deleted_at = Some(Utc::now());
        self.deleted_by = Some(deleter_id);
    }

    /// Restore a soft-deleted record
    pub fn restore(&mut self) {
        self.deleted_at = None;
        self.deleted_by = None;
    }

    /// Check if record is deleted
    pub fn is_deleted(&self) -> bool {
        self.deleted_at.is_some()
    }

    /// Check if record is active (not deleted)
    pub fn is_active(&self) -> bool {
        self.deleted_at.is_none()
    }
}
