//! Livechat Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::ChannelService;
use crate::application::service::ChannelMemberService;
use crate::application::service::ChannelRuleService;
use crate::application::service::ChatbotAnswerService;
use crate::application::service::ChatbotMessageService;
use crate::application::service::ChatbotScriptService;
use crate::application::service::ChatbotStepService;
use crate::application::service::ChatbotStepTriggerService;
use crate::application::service::ConversationTagService;
use crate::application::service::ExpertiseTagService;
use crate::application::service::LivechatAuditLogService;
use crate::application::service::MemberHistoryService;
use crate::application::service::OperatorExpertiseService;
use crate::application::service::OperatorProfileService;
use crate::application::service::RatingService;
use crate::application::service::SessionService;
use crate::application::service::SessionTagService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// Channel service
    pub channel_service: Arc<ChannelService>,
    /// ChannelMember service
    pub channel_member_service: Arc<ChannelMemberService>,
    /// ChannelRule service
    pub channel_rule_service: Arc<ChannelRuleService>,
    /// ChatbotAnswer service
    pub chatbot_answer_service: Arc<ChatbotAnswerService>,
    /// ChatbotMessage service
    pub chatbot_message_service: Arc<ChatbotMessageService>,
    /// ChatbotScript service
    pub chatbot_script_service: Arc<ChatbotScriptService>,
    /// ChatbotStep service
    pub chatbot_step_service: Arc<ChatbotStepService>,
    /// ChatbotStepTrigger service
    pub chatbot_step_trigger_service: Arc<ChatbotStepTriggerService>,
    /// ConversationTag service
    pub conversation_tag_service: Arc<ConversationTagService>,
    /// ExpertiseTag service
    pub expertise_tag_service: Arc<ExpertiseTagService>,
    /// LivechatAuditLog service
    pub livechat_audit_log_service: Arc<LivechatAuditLogService>,
    /// MemberHistory service
    pub member_history_service: Arc<MemberHistoryService>,
    /// OperatorExpertise service
    pub operator_expertise_service: Arc<OperatorExpertiseService>,
    /// OperatorProfile service
    pub operator_profile_service: Arc<OperatorProfileService>,
    /// Rating service
    pub rating_service: Arc<RatingService>,
    /// Session service
    pub session_service: Arc<SessionService>,
    /// SessionTag service
    pub session_tag_service: Arc<SessionTagService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        channel_service: Arc<ChannelService>,
        channel_member_service: Arc<ChannelMemberService>,
        channel_rule_service: Arc<ChannelRuleService>,
        chatbot_answer_service: Arc<ChatbotAnswerService>,
        chatbot_message_service: Arc<ChatbotMessageService>,
        chatbot_script_service: Arc<ChatbotScriptService>,
        chatbot_step_service: Arc<ChatbotStepService>,
        chatbot_step_trigger_service: Arc<ChatbotStepTriggerService>,
        conversation_tag_service: Arc<ConversationTagService>,
        expertise_tag_service: Arc<ExpertiseTagService>,
        livechat_audit_log_service: Arc<LivechatAuditLogService>,
        member_history_service: Arc<MemberHistoryService>,
        operator_expertise_service: Arc<OperatorExpertiseService>,
        operator_profile_service: Arc<OperatorProfileService>,
        rating_service: Arc<RatingService>,
        session_service: Arc<SessionService>,
        session_tag_service: Arc<SessionTagService>
    ) -> Self {
        Self {
            channel_service,
            channel_member_service,
            channel_rule_service,
            chatbot_answer_service,
            chatbot_message_service,
            chatbot_script_service,
            chatbot_step_service,
            chatbot_step_trigger_service,
            conversation_tag_service,
            expertise_tag_service,
            livechat_audit_log_service,
            member_history_service,
            operator_expertise_service,
            operator_profile_service,
            rating_service,
            session_service,
            session_tag_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::LivechatModule) -> Self {
        Self {
            channel_service: module.channel_service.clone(),
            channel_member_service: module.channel_member_service.clone(),
            channel_rule_service: module.channel_rule_service.clone(),
            chatbot_answer_service: module.chatbot_answer_service.clone(),
            chatbot_message_service: module.chatbot_message_service.clone(),
            chatbot_script_service: module.chatbot_script_service.clone(),
            chatbot_step_service: module.chatbot_step_service.clone(),
            chatbot_step_trigger_service: module.chatbot_step_trigger_service.clone(),
            conversation_tag_service: module.conversation_tag_service.clone(),
            expertise_tag_service: module.expertise_tag_service.clone(),
            livechat_audit_log_service: module.livechat_audit_log_service.clone(),
            member_history_service: module.member_history_service.clone(),
            operator_expertise_service: module.operator_expertise_service.clone(),
            operator_profile_service: module.operator_profile_service.clone(),
            rating_service: module.rating_service.clone(),
            session_service: module.session_service.clone(),
            session_tag_service: module.session_tag_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    channel_service: Option<Arc<ChannelService>>,
    channel_member_service: Option<Arc<ChannelMemberService>>,
    channel_rule_service: Option<Arc<ChannelRuleService>>,
    chatbot_answer_service: Option<Arc<ChatbotAnswerService>>,
    chatbot_message_service: Option<Arc<ChatbotMessageService>>,
    chatbot_script_service: Option<Arc<ChatbotScriptService>>,
    chatbot_step_service: Option<Arc<ChatbotStepService>>,
    chatbot_step_trigger_service: Option<Arc<ChatbotStepTriggerService>>,
    conversation_tag_service: Option<Arc<ConversationTagService>>,
    expertise_tag_service: Option<Arc<ExpertiseTagService>>,
    livechat_audit_log_service: Option<Arc<LivechatAuditLogService>>,
    member_history_service: Option<Arc<MemberHistoryService>>,
    operator_expertise_service: Option<Arc<OperatorExpertiseService>>,
    operator_profile_service: Option<Arc<OperatorProfileService>>,
    rating_service: Option<Arc<RatingService>>,
    session_service: Option<Arc<SessionService>>,
    session_tag_service: Option<Arc<SessionTagService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the Channel service.
    pub fn with_channel_service(mut self, service: Arc<ChannelService>) -> Self {
        self.channel_service = Some(service);
        self
    }

    /// Set the ChannelMember service.
    pub fn with_channel_member_service(mut self, service: Arc<ChannelMemberService>) -> Self {
        self.channel_member_service = Some(service);
        self
    }

    /// Set the ChannelRule service.
    pub fn with_channel_rule_service(mut self, service: Arc<ChannelRuleService>) -> Self {
        self.channel_rule_service = Some(service);
        self
    }

    /// Set the ChatbotAnswer service.
    pub fn with_chatbot_answer_service(mut self, service: Arc<ChatbotAnswerService>) -> Self {
        self.chatbot_answer_service = Some(service);
        self
    }

    /// Set the ChatbotMessage service.
    pub fn with_chatbot_message_service(mut self, service: Arc<ChatbotMessageService>) -> Self {
        self.chatbot_message_service = Some(service);
        self
    }

    /// Set the ChatbotScript service.
    pub fn with_chatbot_script_service(mut self, service: Arc<ChatbotScriptService>) -> Self {
        self.chatbot_script_service = Some(service);
        self
    }

    /// Set the ChatbotStep service.
    pub fn with_chatbot_step_service(mut self, service: Arc<ChatbotStepService>) -> Self {
        self.chatbot_step_service = Some(service);
        self
    }

    /// Set the ChatbotStepTrigger service.
    pub fn with_chatbot_step_trigger_service(mut self, service: Arc<ChatbotStepTriggerService>) -> Self {
        self.chatbot_step_trigger_service = Some(service);
        self
    }

    /// Set the ConversationTag service.
    pub fn with_conversation_tag_service(mut self, service: Arc<ConversationTagService>) -> Self {
        self.conversation_tag_service = Some(service);
        self
    }

    /// Set the ExpertiseTag service.
    pub fn with_expertise_tag_service(mut self, service: Arc<ExpertiseTagService>) -> Self {
        self.expertise_tag_service = Some(service);
        self
    }

    /// Set the LivechatAuditLog service.
    pub fn with_livechat_audit_log_service(mut self, service: Arc<LivechatAuditLogService>) -> Self {
        self.livechat_audit_log_service = Some(service);
        self
    }

    /// Set the MemberHistory service.
    pub fn with_member_history_service(mut self, service: Arc<MemberHistoryService>) -> Self {
        self.member_history_service = Some(service);
        self
    }

    /// Set the OperatorExpertise service.
    pub fn with_operator_expertise_service(mut self, service: Arc<OperatorExpertiseService>) -> Self {
        self.operator_expertise_service = Some(service);
        self
    }

    /// Set the OperatorProfile service.
    pub fn with_operator_profile_service(mut self, service: Arc<OperatorProfileService>) -> Self {
        self.operator_profile_service = Some(service);
        self
    }

    /// Set the Rating service.
    pub fn with_rating_service(mut self, service: Arc<RatingService>) -> Self {
        self.rating_service = Some(service);
        self
    }

    /// Set the Session service.
    pub fn with_session_service(mut self, service: Arc<SessionService>) -> Self {
        self.session_service = Some(service);
        self
    }

    /// Set the SessionTag service.
    pub fn with_session_tag_service(mut self, service: Arc<SessionTagService>) -> Self {
        self.session_tag_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            channel_service: self.channel_service.expect("channel_service is required"),
            channel_member_service: self.channel_member_service.expect("channel_member_service is required"),
            channel_rule_service: self.channel_rule_service.expect("channel_rule_service is required"),
            chatbot_answer_service: self.chatbot_answer_service.expect("chatbot_answer_service is required"),
            chatbot_message_service: self.chatbot_message_service.expect("chatbot_message_service is required"),
            chatbot_script_service: self.chatbot_script_service.expect("chatbot_script_service is required"),
            chatbot_step_service: self.chatbot_step_service.expect("chatbot_step_service is required"),
            chatbot_step_trigger_service: self.chatbot_step_trigger_service.expect("chatbot_step_trigger_service is required"),
            conversation_tag_service: self.conversation_tag_service.expect("conversation_tag_service is required"),
            expertise_tag_service: self.expertise_tag_service.expect("expertise_tag_service is required"),
            livechat_audit_log_service: self.livechat_audit_log_service.expect("livechat_audit_log_service is required"),
            member_history_service: self.member_history_service.expect("member_history_service is required"),
            operator_expertise_service: self.operator_expertise_service.expect("operator_expertise_service is required"),
            operator_profile_service: self.operator_profile_service.expect("operator_profile_service is required"),
            rating_service: self.rating_service.expect("rating_service is required"),
            session_service: self.session_service.expect("session_service is required"),
            session_tag_service: self.session_tag_service.expect("session_tag_service is required"),
        }
    }
}
