//! HTTP route configuration
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides consolidated Axum route configuration using backbone-core's
//! BackboneCrudHandler for all 12 standard Backbone CRUD endpoints per entity.

use axum::Router;
use std::sync::Arc;

use super::{
    channel_handler::create_channel_routes,
    channel_member_handler::create_channel_member_routes,
    channel_rule_handler::create_channel_rule_routes,
    chatbot_answer_handler::create_chatbot_answer_routes,
    chatbot_message_handler::create_chatbot_message_read_routes,
    chatbot_script_handler::create_chatbot_script_routes,
    chatbot_step_handler::create_chatbot_step_routes,
    chatbot_step_trigger_handler::create_chatbot_step_trigger_routes,
    conversation_tag_handler::create_conversation_tag_routes,
    expertise_tag_handler::create_expertise_tag_routes,
    livechat_audit_log_handler::create_livechat_audit_log_read_routes,
    member_history_handler::create_member_history_read_routes,
    operator_expertise_handler::create_operator_expertise_routes,
    operator_profile_handler::create_operator_profile_routes,
    rating_handler::create_rating_routes,
    session_handler::create_session_read_routes,
    session_tag_handler::create_session_tag_routes,
};

use crate::application::service::{
    ChannelService,
    ChannelMemberService,
    ChannelRuleService,
    ChatbotAnswerService,
    ChatbotMessageService,
    ChatbotScriptService,
    ChatbotStepService,
    ChatbotStepTriggerService,
    ConversationTagService,
    ExpertiseTagService,
    LivechatAuditLogService,
    MemberHistoryService,
    OperatorExpertiseService,
    OperatorProfileService,
    RatingService,
    SessionService,
    SessionTagService,
};

/// Services collection for all CRUD endpoints
pub struct HttpServices {
    pub channel: Arc<ChannelService>,
    pub channel_member: Arc<ChannelMemberService>,
    pub channel_rule: Arc<ChannelRuleService>,
    pub chatbot_answer: Arc<ChatbotAnswerService>,
    pub chatbot_message: Arc<ChatbotMessageService>,
    pub chatbot_script: Arc<ChatbotScriptService>,
    pub chatbot_step: Arc<ChatbotStepService>,
    pub chatbot_step_trigger: Arc<ChatbotStepTriggerService>,
    pub conversation_tag: Arc<ConversationTagService>,
    pub expertise_tag: Arc<ExpertiseTagService>,
    pub livechat_audit_log: Arc<LivechatAuditLogService>,
    pub member_history: Arc<MemberHistoryService>,
    pub operator_expertise: Arc<OperatorExpertiseService>,
    pub operator_profile: Arc<OperatorProfileService>,
    pub rating: Arc<RatingService>,
    pub session: Arc<SessionService>,
    pub session_tag: Arc<SessionTagService>,
}

/// Configure all HTTP routes for this module using Axum and BackboneCrudHandler.
///
/// Each entity gets 12 standard Backbone CRUD endpoints:
/// 1. GET /api/v1/{collection} - List with pagination
/// 2. POST /api/v1/{collection} - Create
/// 3. GET /api/v1/{collection}/:id - Get by ID
/// 4. PUT /api/v1/{collection}/:id - Full update
/// 5. PATCH /api/v1/{collection}/:id - Partial update
/// 6. DELETE /api/v1/{collection}/:id - Soft delete
/// 7. POST /api/v1/{collection}/bulk - Bulk create
/// 8. POST /api/v1/{collection}/upsert - Upsert
/// 9. GET /api/v1/{collection}/trash - List deleted
/// 10. POST /api/v1/{collection}/:id/restore - Restore
/// 11. DELETE /api/v1/{collection}/empty - Empty trash
/// 12. GET /api/v1/{collection}/:id/deleted - Get deleted by ID
pub fn configure_routes(services: HttpServices) -> Router {
    Router::new()
        // Channel routes (12 Backbone endpoints)
        .merge(create_channel_routes(services.channel))
        // ChannelMember routes (12 Backbone endpoints)
        .merge(create_channel_member_routes(services.channel_member))
        // ChannelRule routes (12 Backbone endpoints)
        .merge(create_channel_rule_routes(services.channel_rule))
        // ChatbotAnswer routes (12 Backbone endpoints)
        .merge(create_chatbot_answer_routes(services.chatbot_answer))
        // ChatbotMessage routes (READ-ONLY — append-only/event-sourced entity; writes arrive via the event handlers)
        .merge(create_chatbot_message_read_routes(services.chatbot_message))
        // ChatbotScript routes (12 Backbone endpoints)
        .merge(create_chatbot_script_routes(services.chatbot_script))
        // ChatbotStep routes (12 Backbone endpoints)
        .merge(create_chatbot_step_routes(services.chatbot_step))
        // ChatbotStepTrigger routes (12 Backbone endpoints)
        .merge(create_chatbot_step_trigger_routes(services.chatbot_step_trigger))
        // ConversationTag routes (12 Backbone endpoints)
        .merge(create_conversation_tag_routes(services.conversation_tag))
        // ExpertiseTag routes (12 Backbone endpoints)
        .merge(create_expertise_tag_routes(services.expertise_tag))
        // LivechatAuditLog routes (READ-ONLY — append-only/event-sourced entity; writes arrive via the event handlers)
        .merge(create_livechat_audit_log_read_routes(services.livechat_audit_log))
        // MemberHistory routes (READ-ONLY — append-only/event-sourced entity; writes arrive via the event handlers)
        .merge(create_member_history_read_routes(services.member_history))
        // OperatorExpertise routes (12 Backbone endpoints)
        .merge(create_operator_expertise_routes(services.operator_expertise))
        // OperatorProfile routes (12 Backbone endpoints)
        .merge(create_operator_profile_routes(services.operator_profile))
        // Rating routes (12 Backbone endpoints)
        .merge(create_rating_routes(services.rating))
        // Session routes (READ-ONLY — append-only/event-sourced entity; writes arrive via the event handlers)
        .merge(create_session_read_routes(services.session))
        // SessionTag routes (12 Backbone endpoints)
        .merge(create_session_tag_routes(services.session_tag))
}

/// Create an individual entity's routes (for modular configuration)
pub mod individual {
    use super::*;

    pub fn channel_routes(service: Arc<ChannelService>) -> Router {
        create_channel_routes(service)
    }

    pub fn channel_member_routes(service: Arc<ChannelMemberService>) -> Router {
        create_channel_member_routes(service)
    }

    pub fn channel_rule_routes(service: Arc<ChannelRuleService>) -> Router {
        create_channel_rule_routes(service)
    }

    pub fn chatbot_answer_routes(service: Arc<ChatbotAnswerService>) -> Router {
        create_chatbot_answer_routes(service)
    }

    pub fn chatbot_message_routes(service: Arc<ChatbotMessageService>) -> Router {
        create_chatbot_message_routes(service)
    }

    pub fn chatbot_script_routes(service: Arc<ChatbotScriptService>) -> Router {
        create_chatbot_script_routes(service)
    }

    pub fn chatbot_step_routes(service: Arc<ChatbotStepService>) -> Router {
        create_chatbot_step_routes(service)
    }

    pub fn chatbot_step_trigger_routes(service: Arc<ChatbotStepTriggerService>) -> Router {
        create_chatbot_step_trigger_routes(service)
    }

    pub fn conversation_tag_routes(service: Arc<ConversationTagService>) -> Router {
        create_conversation_tag_routes(service)
    }

    pub fn expertise_tag_routes(service: Arc<ExpertiseTagService>) -> Router {
        create_expertise_tag_routes(service)
    }

    pub fn livechat_audit_log_routes(service: Arc<LivechatAuditLogService>) -> Router {
        create_livechat_audit_log_routes(service)
    }

    pub fn member_history_routes(service: Arc<MemberHistoryService>) -> Router {
        create_member_history_routes(service)
    }

    pub fn operator_expertise_routes(service: Arc<OperatorExpertiseService>) -> Router {
        create_operator_expertise_routes(service)
    }

    pub fn operator_profile_routes(service: Arc<OperatorProfileService>) -> Router {
        create_operator_profile_routes(service)
    }

    pub fn rating_routes(service: Arc<RatingService>) -> Router {
        create_rating_routes(service)
    }

    pub fn session_routes(service: Arc<SessionService>) -> Router {
        create_session_routes(service)
    }

    pub fn session_tag_routes(service: Arc<SessionTagService>) -> Router {
        create_session_tag_routes(service)
    }

}
