//! Public events for Livechat module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use super::types::*;

// ============================================================================
// CHANNEL EVENTS
// ============================================================================

/// Event published when a Channel is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChannelCreatedEvent {
    pub id: ChannelId,
    pub data: ChannelDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Channel is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChannelUpdatedEvent {
    pub id: ChannelId,
    pub data: ChannelDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Channel is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChannelDeletedEvent {
    pub id: ChannelId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// CHANNELMEMBER EVENTS
// ============================================================================

/// Event published when a ChannelMember is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChannelMemberCreatedEvent {
    pub id: ChannelMemberId,
    pub data: ChannelMemberDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ChannelMember is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChannelMemberUpdatedEvent {
    pub id: ChannelMemberId,
    pub data: ChannelMemberDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ChannelMember is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChannelMemberDeletedEvent {
    pub id: ChannelMemberId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// CHANNELRULE EVENTS
// ============================================================================

/// Event published when a ChannelRule is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChannelRuleCreatedEvent {
    pub id: ChannelRuleId,
    pub data: ChannelRuleDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ChannelRule is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChannelRuleUpdatedEvent {
    pub id: ChannelRuleId,
    pub data: ChannelRuleDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ChannelRule is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChannelRuleDeletedEvent {
    pub id: ChannelRuleId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// CHATBOTANSWER EVENTS
// ============================================================================

/// Event published when a ChatbotAnswer is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatbotAnswerCreatedEvent {
    pub id: ChatbotAnswerId,
    pub data: ChatbotAnswerDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ChatbotAnswer is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatbotAnswerUpdatedEvent {
    pub id: ChatbotAnswerId,
    pub data: ChatbotAnswerDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ChatbotAnswer is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatbotAnswerDeletedEvent {
    pub id: ChatbotAnswerId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// CHATBOTMESSAGE EVENTS
// ============================================================================

/// Event published when a ChatbotMessage is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatbotMessageCreatedEvent {
    pub id: ChatbotMessageId,
    pub data: ChatbotMessageDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ChatbotMessage is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatbotMessageUpdatedEvent {
    pub id: ChatbotMessageId,
    pub data: ChatbotMessageDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ChatbotMessage is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatbotMessageDeletedEvent {
    pub id: ChatbotMessageId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// CHATBOTSCRIPT EVENTS
// ============================================================================

/// Event published when a ChatbotScript is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatbotScriptCreatedEvent {
    pub id: ChatbotScriptId,
    pub data: ChatbotScriptDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ChatbotScript is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatbotScriptUpdatedEvent {
    pub id: ChatbotScriptId,
    pub data: ChatbotScriptDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ChatbotScript is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatbotScriptDeletedEvent {
    pub id: ChatbotScriptId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// CHATBOTSTEP EVENTS
// ============================================================================

/// Event published when a ChatbotStep is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatbotStepCreatedEvent {
    pub id: ChatbotStepId,
    pub data: ChatbotStepDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ChatbotStep is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatbotStepUpdatedEvent {
    pub id: ChatbotStepId,
    pub data: ChatbotStepDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ChatbotStep is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatbotStepDeletedEvent {
    pub id: ChatbotStepId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// CHATBOTSTEPTRIGGER EVENTS
// ============================================================================

/// Event published when a ChatbotStepTrigger is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatbotStepTriggerCreatedEvent {
    pub id: ChatbotStepTriggerId,
    pub data: ChatbotStepTriggerDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ChatbotStepTrigger is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatbotStepTriggerUpdatedEvent {
    pub id: ChatbotStepTriggerId,
    pub data: ChatbotStepTriggerDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ChatbotStepTrigger is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatbotStepTriggerDeletedEvent {
    pub id: ChatbotStepTriggerId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// CONVERSATIONTAG EVENTS
// ============================================================================

/// Event published when a ConversationTag is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConversationTagCreatedEvent {
    pub id: ConversationTagId,
    pub data: ConversationTagDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ConversationTag is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConversationTagUpdatedEvent {
    pub id: ConversationTagId,
    pub data: ConversationTagDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ConversationTag is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConversationTagDeletedEvent {
    pub id: ConversationTagId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// EXPERTISETAG EVENTS
// ============================================================================

/// Event published when a ExpertiseTag is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExpertiseTagCreatedEvent {
    pub id: ExpertiseTagId,
    pub data: ExpertiseTagDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ExpertiseTag is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExpertiseTagUpdatedEvent {
    pub id: ExpertiseTagId,
    pub data: ExpertiseTagDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ExpertiseTag is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExpertiseTagDeletedEvent {
    pub id: ExpertiseTagId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// LIVECHATAUDITLOG EVENTS
// ============================================================================

/// Event published when a LivechatAuditLog is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LivechatAuditLogCreatedEvent {
    pub id: LivechatAuditLogId,
    pub data: LivechatAuditLogDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a LivechatAuditLog is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LivechatAuditLogUpdatedEvent {
    pub id: LivechatAuditLogId,
    pub data: LivechatAuditLogDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a LivechatAuditLog is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LivechatAuditLogDeletedEvent {
    pub id: LivechatAuditLogId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MEMBERHISTORY EVENTS
// ============================================================================

/// Event published when a MemberHistory is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MemberHistoryCreatedEvent {
    pub id: MemberHistoryId,
    pub data: MemberHistoryDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a MemberHistory is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MemberHistoryUpdatedEvent {
    pub id: MemberHistoryId,
    pub data: MemberHistoryDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a MemberHistory is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MemberHistoryDeletedEvent {
    pub id: MemberHistoryId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// OPERATOREXPERTISE EVENTS
// ============================================================================

/// Event published when a OperatorExpertise is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OperatorExpertiseCreatedEvent {
    pub id: OperatorExpertiseId,
    pub data: OperatorExpertiseDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a OperatorExpertise is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OperatorExpertiseUpdatedEvent {
    pub id: OperatorExpertiseId,
    pub data: OperatorExpertiseDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a OperatorExpertise is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OperatorExpertiseDeletedEvent {
    pub id: OperatorExpertiseId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// OPERATORPROFILE EVENTS
// ============================================================================

/// Event published when a OperatorProfile is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OperatorProfileCreatedEvent {
    pub id: OperatorProfileId,
    pub data: OperatorProfileDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a OperatorProfile is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OperatorProfileUpdatedEvent {
    pub id: OperatorProfileId,
    pub data: OperatorProfileDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a OperatorProfile is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OperatorProfileDeletedEvent {
    pub id: OperatorProfileId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// RATING EVENTS
// ============================================================================

/// Event published when a Rating is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RatingCreatedEvent {
    pub id: RatingId,
    pub data: RatingDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Rating is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RatingUpdatedEvent {
    pub id: RatingId,
    pub data: RatingDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Rating is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RatingDeletedEvent {
    pub id: RatingId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// SESSION EVENTS
// ============================================================================

/// Event published when a Session is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionCreatedEvent {
    pub id: SessionId,
    pub data: SessionDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Session is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionUpdatedEvent {
    pub id: SessionId,
    pub data: SessionDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Session is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionDeletedEvent {
    pub id: SessionId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// SESSIONTAG EVENTS
// ============================================================================

/// Event published when a SessionTag is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionTagCreatedEvent {
    pub id: SessionTagId,
    pub data: SessionTagDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a SessionTag is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionTagUpdatedEvent {
    pub id: SessionTagId,
    pub data: SessionTagDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a SessionTag is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionTagDeletedEvent {
    pub id: SessionTagId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by Livechat module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum LivechatEvent {
    ChannelCreated(ChannelCreatedEvent),
    ChannelUpdated(ChannelUpdatedEvent),
    ChannelDeleted(ChannelDeletedEvent),
    ChannelMemberCreated(ChannelMemberCreatedEvent),
    ChannelMemberUpdated(ChannelMemberUpdatedEvent),
    ChannelMemberDeleted(ChannelMemberDeletedEvent),
    ChannelRuleCreated(ChannelRuleCreatedEvent),
    ChannelRuleUpdated(ChannelRuleUpdatedEvent),
    ChannelRuleDeleted(ChannelRuleDeletedEvent),
    ChatbotAnswerCreated(ChatbotAnswerCreatedEvent),
    ChatbotAnswerUpdated(ChatbotAnswerUpdatedEvent),
    ChatbotAnswerDeleted(ChatbotAnswerDeletedEvent),
    ChatbotMessageCreated(ChatbotMessageCreatedEvent),
    ChatbotMessageUpdated(ChatbotMessageUpdatedEvent),
    ChatbotMessageDeleted(ChatbotMessageDeletedEvent),
    ChatbotScriptCreated(ChatbotScriptCreatedEvent),
    ChatbotScriptUpdated(ChatbotScriptUpdatedEvent),
    ChatbotScriptDeleted(ChatbotScriptDeletedEvent),
    ChatbotStepCreated(ChatbotStepCreatedEvent),
    ChatbotStepUpdated(ChatbotStepUpdatedEvent),
    ChatbotStepDeleted(ChatbotStepDeletedEvent),
    ChatbotStepTriggerCreated(ChatbotStepTriggerCreatedEvent),
    ChatbotStepTriggerUpdated(ChatbotStepTriggerUpdatedEvent),
    ChatbotStepTriggerDeleted(ChatbotStepTriggerDeletedEvent),
    ConversationTagCreated(ConversationTagCreatedEvent),
    ConversationTagUpdated(ConversationTagUpdatedEvent),
    ConversationTagDeleted(ConversationTagDeletedEvent),
    ExpertiseTagCreated(ExpertiseTagCreatedEvent),
    ExpertiseTagUpdated(ExpertiseTagUpdatedEvent),
    ExpertiseTagDeleted(ExpertiseTagDeletedEvent),
    LivechatAuditLogCreated(LivechatAuditLogCreatedEvent),
    LivechatAuditLogUpdated(LivechatAuditLogUpdatedEvent),
    LivechatAuditLogDeleted(LivechatAuditLogDeletedEvent),
    MemberHistoryCreated(MemberHistoryCreatedEvent),
    MemberHistoryUpdated(MemberHistoryUpdatedEvent),
    MemberHistoryDeleted(MemberHistoryDeletedEvent),
    OperatorExpertiseCreated(OperatorExpertiseCreatedEvent),
    OperatorExpertiseUpdated(OperatorExpertiseUpdatedEvent),
    OperatorExpertiseDeleted(OperatorExpertiseDeletedEvent),
    OperatorProfileCreated(OperatorProfileCreatedEvent),
    OperatorProfileUpdated(OperatorProfileUpdatedEvent),
    OperatorProfileDeleted(OperatorProfileDeletedEvent),
    RatingCreated(RatingCreatedEvent),
    RatingUpdated(RatingUpdatedEvent),
    RatingDeleted(RatingDeletedEvent),
    SessionCreated(SessionCreatedEvent),
    SessionUpdated(SessionUpdatedEvent),
    SessionDeleted(SessionDeletedEvent),
    SessionTagCreated(SessionTagCreatedEvent),
    SessionTagUpdated(SessionTagUpdatedEvent),
    SessionTagDeleted(SessionTagDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LivechatEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for LivechatEventMetadata {
    fn default() -> Self {
        Self {
            module: "livechat",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
